using System;

namespace POEStash
{
    public enum ItemType
    {
        Unknown,
        Amulet,
        Talisman,
        Ring,
        Belt,
        Quiver,
        BodyArmour,
        Boots,
        Gloves,
        Helmet,
        Shield,
        Bow,
        Claw,
        Dagger,
        OneHandedAxe,
        OneHandedMace,
        OneHandedSword,
        Sceptre,
        Staff,
        OneHandedThrustingSword,
        TwoHandedAxe,
        TwoHandedMace,
        TwoHandedSword,
        Wand,
        Jewel,
        Map,
        MapFragment,
        SkillGem,
        DivinationCard,
        Currency,
        Flask
    }

    public static class BaseTypes
    {
        public static ItemType GetItemType(string typeString)
        {
            if (IsUniqueAndGetItemType(typeString, out ItemType itemType))
            {
                return itemType;
            }

            if (Matches(BaseTypesAmulets.BaseTypes, typeString)) return ItemType.Amulet;
            if (Matches(BaseTypesRings.BaseTypes, typeString)) return ItemType.Ring;
            if (Matches(BaseTypesBelt.BaseTypes, typeString)) return ItemType.Belt;
            if (Matches(BaseTypesQuivers.BaseTypes, typeString)) return ItemType.Quiver;
            if (Matches(BaseTypesTalismans.BaseTypes, typeString)) return ItemType.Talisman;
            if (Matches(BaseTypesBodyArmour.BaseTypes, typeString)) return ItemType.BodyArmour;
            if (Matches(BaseTypesBoots.BaseTypes, typeString)) return ItemType.Boots;
            if (Matches(BaseTypesGloves.BaseTypes, typeString)) return ItemType.Gloves;
            if (Matches(BaseTypesHelmets.BaseTypes, typeString)) return ItemType.Helmet;
            if (Matches(BaseTypesShields.BaseTypes, typeString)) return ItemType.Shield;
            if (Matches(BaseTypesBows.BaseTypes, typeString)) return ItemType.Bow;
            if (Matches(BaseTypesClaws.BaseTypes, typeString)) return ItemType.Claw;
            if (Matches(BaseTypesDaggers.BaseTypes, typeString)) return ItemType.Dagger;
            if (Matches(BaseTypesOneHandedAxes.BaseTypes, typeString)) return ItemType.OneHandedAxe;
            if (Matches(BaseTypesOneHandedMaces.BaseTypes, typeString)) return ItemType.OneHandedMace;
            if (Matches(BaseTypesOneHandedSwords.BaseTypes, typeString)) return ItemType.OneHandedSword;
            if (Matches(BaseTypesSceptres.BaseTypes, typeString)) return ItemType.Sceptre;
            if (Matches(BaseTypesStaffs.BaseTypes, typeString)) return ItemType.Staff;
            if (Matches(BaseTypesThrustingOneHandedSwords.BaseTypes, typeString)) return ItemType.OneHandedThrustingSword;
            if (Matches(BaseTypesTwoHandedAxes.BaseTypes, typeString)) return ItemType.TwoHandedAxe;
            if (Matches(BaseTypesTwoHandedMaces.BaseTypes, typeString)) return ItemType.TwoHandedMace;
            if (Matches(BaseTypesTwoHandedSwords.BaseTypes, typeString)) return ItemType.TwoHandedSword;
            if (Matches(BaseTypesWands.BaseTypes, typeString)) return ItemType.Wand;
            if (Matches(BaseTypesJewels.BaseTypes, typeString)) return ItemType.Jewel;
            if (Matches(BaseTypesMaps.BaseTypes, typeString)) return ItemType.Map;
            if (Matches(BaseTypesMapFragments.BaseTypes, typeString)) return ItemType.MapFragment;
            if (Matches(BaseTypesSkillGems.BaseTypes, typeString)) return ItemType.SkillGem;
            if (Matches(BaseTypesDivinationCards.BaseTypes, typeString)) return ItemType.DivinationCard;
            if (Matches(BaseTypesCurrencies.BaseTypes, typeString)) return ItemType.Currency;
            if (Matches(BaseTypesFlasks.BaseTypes, typeString)) return ItemType.Flask;

            return ItemType.Unknown;
        }

        private static bool Matches(string[] baseTypes, string typeString)
        {
            foreach (string baseType in baseTypes)
            {
                if (typeString.IndexOf(baseType, 0, StringComparison.OrdinalIgnoreCase) != -1)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsUniqueAndGetItemType(string typeString, out ItemType type)
        {
            type = ItemType.Unknown;

            foreach (Unique unique in Uniques.AllUniques)
            {
                if (typeString.IndexOf(unique.ItemName, 0, StringComparison.OrdinalIgnoreCase) != -1)
                {
                    type = unique.ItemType;
                    return true;
                }
            }

            return false;
        }

        public static bool IsUnique(string typeString)
        {
            foreach (Unique unique in Uniques.AllUniques)
            {
                if (string.Equals(typeString, unique.ItemName, StringComparison.OrdinalIgnoreCase)) 
                {
                    return true;
                }
            }

            return false;
        }
    }

    public static class BaseTypesAmulets
    {
        public static string[] BaseTypes =
        {
            "Coral Amulet",
            "Paua Amulet",
            "Amber Amulet",
            "Jade Amulet",
            "Lapis Amulet",
            "Gold Amulet",
            "Agate Amulet",
            "Citrine Amulet",
            "Turquoise Amulet",
            "Onyx Amulet",
            "Marble Amulet",
            "Blue Pearl Amulet"
        };
    }

    public static class BaseTypesRings
    {
        public static string[] BaseTypes =
        {
            "Breach Ring",
            "Iron Ring",
            "Coral Ring",
            "Paua Ring",
            "Sapphire Ring",
            "Topaz Ring",
            "Golden Hoop",
            "Jet Ring",
            "Ruby Ring",
            "Gold Ring",
            "Two-Stone Ring",
            "Diamond Ring",
            "Moonstone Ring",
            "Prismatic Ring",
            "Amethyst Ring",
            "Unset Ring",
            "Steel Ring",
            "Opal Ring",
        };
    }

    public static class BaseTypesBelt
    {
        public static string[] BaseTypes =
        {
            "Chain Belt",
            "Rustic Sash",
            "Heavy Belt",
            "Leather Belt",
            "Cloth Belt",
            "Studded Belt",
            "Vanguard Belt",
            "Crystal Belt"
        };
    }

    public static class BaseTypesQuivers
    {
        public static string[] BaseTypes =
        {
            "Two-Point Arrow Quiver",
            "Serrated Arrow Quiver",
            "Sharktooth Arrow Quiver",
            "Blunt Arrow Quiver",
            "Fire Arrow Quiver",
            "Broadhead Arrow Quiver",
            "Penetrating Arrow Quiver",
            "Spike-Point Arrow Quiver",
        };
    }

    public static class BaseTypesTalismans
    {
        public static string[] BaseTypes =
        {
            "Spinefuse Talisman",
            "Mandible Talisman",
            "Hexclaw Talisman",
            "Primal Skull Talisman",
            "Wereclaw Talisman",
            "Splitnewt Talisman",
            "Clutching Talisman",
            "Avian Twins Talisman",
            "Fangjaw Talisman",
            "Horned Talisman",
            "Three Rat Talisman",
            "Monkey Twins Talisman",
            "Longtooth Talisman",
            "Rotfeather Talisman",
            "Monkey Paw Talisman",
            "Three Hands Talisman",
            "Jet Amulet",
            "Black Maw Talisman",
            "Bonespire Talisman",
            "Ashscale Talisman",
            "Lone Antler Talisman",
            "Deep One Talisman",
            "Breakrib Talisman",
            "Deadhand Talisman",
            "Undying Flesh Talisman",
            "Rot Head Talisman",
            "Writhing Talisman",
            "Chrysalis Talisman",
            "Greatwolf Talisman"
        };
    }

    public static class BaseTypesBodyArmour
    {
        public static string[] BaseTypes =
        {
            "Plate Vest",
            "Shabby Jerkin",
            "Simple Robe",
            "Chainmail Vest",
            "Scale Vest",
            "Padded Vest",
            "Chestplate",
            "Light Brigandine",
            "Chainmail Tunic",
            "Oiled Vest",
            "Strapped Leather",
            "Silken Vest",
            "Scale Doublet",
            "Ringmail Coat",
            "Copper Plate",
            "Buckskin Tunic",
            "Padded Jacket",
            "Scholar's Robe",
            "Infantry Brigandine",
            "Chainmail Doublet",
            "War Plate",
            "Oiled Coat",
            "Wild Leather",
            "Silken Garb",
            "Full Plate",
            "Mage's Vestment",
            "Scarlet Raiment",
            "Full Ringmail",
            "Full Scale Armour",
            "Full Leather",
            "Soldier's Brigandine",
            "Silk Robe",
            "Waxed Garb",
            "Arena Plate",
            "Sun Leather",
            "Full Chainmail",
            "Holy Chainmail",
            "Lordly Plate",
            "Thief's Garb",
            "Cabalist Regalia",
            "Field Lamellar",
            "Bone Armour",
            "Eelskin Tunic",
            "Bronze Plate",
            "Sage's Robe",
            "Wyrmscale Doublet",
            "Latticed Ringmail",
            "Quilted Jacket",
            "Silken Wrap",
            "Battle Plate",
            "Frontier Leather",
            "Hussar Brigandine",
            "Crusader Chainmail",
            "Sleek Coat",
            "Sun Plate",
            "Conjurer's Vestment",
            "Glorious Leather",
            "Full Wyrmscale",
            "Ornate Ringmail",
            "Crimson Raiment",
            "Colosseum Plate",
            "Coronal Leather",
            "Spidersilk Robe",
            "Commander's Brigandine",
            "Chain Hauberk",
            "Lacquered Garb",
            "Majestic Plate",
            "Cutthroat's Garb",
            "Destroyer Regalia",
            "Battle Lamellar",
            "Devout Chainmail",
            "Crypt Armour",
            "Savant's Robe",
            "Sharkskin Tunic",
            "Golden Plate",
            "Dragonscale Doublet",
            "Loricated Ringmail",
            "Sentinel Jacket",
            "Necromancer Silks",
            "Crusader Plate",
            "Destiny Leather",
            "Desert Brigandine",
            "Conquest Chainmail",
            "Occultist's Vestment",
            "Exquisite Leather",
            "Astral Plate",
            "Varnished Coat",
            "Full Dragonscale",
            "Elegant Ringmail",
            "Zodiac Leather",
            "Gladiator Plate",
            "Widowsilk Robe",
            "Blood Raiment",
            "General's Brigandine",
            "Saint's Hauberk",
            "Glorious Plate",
            "Assassin's Garb",
            "Vaal Regalia",
            "Sadist Garb",
            "Triumphant Lamellar",
            "Saintly Chainmail",
            "Carnal Armour",
            "Sacrificial Garb"
        };
    }

    public static class BaseTypesBoots
    {
        public static string[] BaseTypes =
        {
            "Iron Greaves",
            "Rawhide Boots",
            "Wool Shoes",
            "Chain Boots",
            "Wrapped Boots",
            "Leatherscale Boots",
            "Velvet Slippers",
            "Steel Greaves",
            "Goathide Boots",
            "Ringmail Boots",
            "Strapped Boots",
            "Ironscale Boots",
            "Deerskin Boots",
            "Silk Slippers",
            "Plated Greaves",
            "Clasped Boots",
            "Mesh Boots",
            "Bronzescale Boots",
            "Scholar Boots",
            "Reinforced Greaves",
            "Nubuck Boots",
            "Shackled Boots",
            "Steelscale Boots",
            "Riveted Boots",
            "Antique Greaves",
            "Satin Slippers",
            "Eelskin Boots",
            "Zealot Boots",
            "Trapper Boots",
            "Serpentscale Boots",
            "Samite Slippers",
            "Sharkskin Boots",
            "Ancient Greaves",
            "Ambush Boots",
            "Soldier Boots",
            "Wyrmscale Boots",
            "Conjurer Boots",
            "Goliath Greaves",
            "Carnal Boots",
            "Shagreen Boots",
            "Legion Boots",
            "Hydrascale Boots",
            "Arcanist Slippers",
            "Vaal Greaves",
            "Stealth Boots",
            "Assassin's Boots",
            "Crusader Boots",
            "Dragonscale Boots",
            "Sorcerer Boots",
            "Titan Greaves",
            "Slink Boots",
            "Murder Boots",
            "Two-Toned Boots",
        };
    }

    public static class BaseTypesGloves
    {
        public static string[] BaseTypes =
        {
            "Iron Gauntlets",
            "Rawhide Gloves",
            "Wool Gloves",
            "Fishscale Gauntlets",
            "Wrapped Mitts",
            "Chain Gloves",
            "Goathide Gloves",
            "Plated Gauntlets",
            "Velvet Gloves",
            "Ironscale Gauntlets",
            "Strapped Mitts",
            "Ringmail Gloves",
            "Deerskin Gloves",
            "Bronze Gauntlets",
            "Silk Gloves",
            "Bronzescale Gauntlets",
            "Clasped Mitts",
            "Mesh Gloves",
            "Nubuck Gloves",
            "Steel Gauntlets",
            "Embroidered Gloves",
            "Trapper Mitts",
            "Steelscale Gauntlets",
            "Riveted Gloves",
            "Eelskin Gloves",
            "Antique Gauntlets",
            "Satin Gloves",
            "Zealot Gloves",
            "Serpentscale Gauntlets",
            "Ambush Mitts",
            "Sharkskin Gloves",
            "Samite Gloves",
            "Ancient Gauntlets",
            "Wyrmscale Gauntlets",
            "Carnal Mitts",
            "Soldier Gloves",
            "Goliath Gauntlets",
            "Shagreen Gloves",
            "Conjurer Gloves",
            "Legion Gloves",
            "Assassin's Mitts",
            "Hydrascale Gauntlets",
            "Arcanist Gloves",
            "Stealth Gloves",
            "Vaal Gauntlets",
            "Crusader Gloves",
            "Murder Mitts",
            "Dragonscale Gauntlets",
            "Titan Gauntlets",
            "Sorcerer Gloves",
            "Slink Gloves",
            "Gripped Gloves",
            "Fingerless Silk Gloves",
            "Spiked Gloves",
        };
    }

    public static class BaseTypesHelmets
    {
        public static string[] BaseTypes =
        {
            "Iron Hat",
            "Vine Circlet",
            "Leather Cap",
            "Scare Mask",
            "Battered Helm",
            "Rusted Coif",
            "Cone Helmet",
            "Iron Circlet",
            "Tricorne",
            "Plague Mask",
            "Soldier Helmet",
            "Sallet",
            "Iron Mask",
            "Torture Cage",
            "Barbute Helmet",
            "Leather Hood",
            "Great Helmet",
            "Visored Sallet",
            "Close Helmet",
            "Tribal Circlet",
            "Festival Mask",
            "Wolf Pelt",
            "Crusader Helmet",
            "Gilded Sallet",
            "Bone Circlet",
            "Gladiator Helmet",
            "Golden Mask",
            "Secutor Helm",
            "Aventail Helmet",
            "Raven Mask",
            "Lunaris Circlet",
            "Reaver Helmet",
            "Hunter Hood",
            "Fencer Helm",
            "Zealot Helmet",
            "Callous Mask",
            "Noble Tricorne",
            "Steel Circlet",
            "Siege Helmet",
            "Lacquered Helmet",
            "Regicide Mask",
            "Great Crown",
            "Necromancer Circlet",
            "Ursine Pelt",
            "Samite Helmet",
            "Harlequin Mask",
            "Magistrate Crown",
            "Fluted Bascinet",
            "Solaris Circlet",
            "Silken Hood",
            "Ezomyte Burgonet",
            "Vaal Mask",
            "Pig-Faced Bascinet",
            "Prophet Crown",
            "Sinner Tricorne",
            "Mind Cage",
            "Royal Burgonet",
            "Deicide Mask",
            "Nightmare Bascinet",
            "Praetor Crown",
            "Hubris Circlet",
            "Eternal Burgonet",
            "Lion Pelt",
            "Bone Helmet",
        };
    }

    public static class BaseTypesShields
    {
        public static string[] BaseTypes =
        {
            "Splintered Tower Shield",
            "Goathide Buckler",
            "Twig Spirit Shield",
            "Spiked Bundle",
            "Corroded Tower Shield",
            "Rotted Round Shield",
            "Plank Kite Shield",
            "Pine Buckler",
            "Yew Spirit Shield",
            "Rawhide Tower Shield",
            "Fir Round Shield",
            "Driftwood Spiked Shield",
            "Linden Kite Shield",
            "Bone Spirit Shield",
            "Painted Buckler",
            "Cedar Tower Shield",
            "Reinforced Kite Shield",
            "Alloyed Spiked Shield",
            "Studded Round Shield",
            "Hammered Buckler",
            "Tarnished Spirit Shield",
            "Copper Tower Shield",
            "Layered Kite Shield",
            "Scarlet Round Shield",
            "Burnished Spiked Shield",
            "Jingling Spirit Shield",
            "War Buckler",
            "Reinforced Tower Shield",
            "Splendid Round Shield",
            "Ornate Spiked Shield",
            "Brass Spirit Shield",
            "Ceremonial Kite Shield",
            "Gilded Buckler",
            "Painted Tower Shield",
            "Walnut Spirit Shield",
            "Oak Buckler",
            "Buckskin Tower Shield",
            "Maple Round Shield",
            "Redwood Spiked Shield",
            "Etched Kite Shield",
            "Ivory Spirit Shield",
            "Enameled Buckler",
            "Mahogany Tower Shield",
            "Ancient Spirit Shield",
            "Spiked Round Shield",
            "Compound Spiked Shield",
            "Corrugated Buckler",
            "Steel Kite Shield",
            "Bronze Tower Shield",
            "Chiming Spirit Shield",
            "Crimson Round Shield",
            "Polished Spiked Shield",
            "Battle Buckler",
            "Laminated Kite Shield",
            "Girded Tower Shield",
            "Thorium Spirit Shield",
            "Sovereign Spiked Shield",
            "Golden Buckler",
            "Baroque Round Shield",
            "Angelic Kite Shield",
            "Crested Tower Shield",
            "Lacewood Spirit Shield",
            "Ironwood Buckler",
            "Alder Spiked Shield",
            "Shagreen Tower Shield",
            "Teak Round Shield",
            "Branded Kite Shield",
            "Fossilised Spirit Shield",
            "Lacquered Buckler",
            "Ebony Tower Shield",
            "Champion Kite Shield",
            "Vaal Spirit Shield",
            "Spiny Round Shield",
            "Ezomyte Spiked Shield",
            "Vaal Buckler",
            "Ezomyte Tower Shield",
            "Mosaic Kite Shield",
            "Harmonic Spirit Shield",
            "Cardinal Round Shield",
            "Mirrored Spiked Shield",
            "Crusader Buckler",
            "Colossal Tower Shield",
            "Archon Kite Shield",
            "Titanium Spirit Shield",
            "Imperial Buckler",
            "Supreme Spiked Shield",
            "Pinnacle Tower Shield",
            "Elegant Round Shield",
        };
    }

    public static class BaseTypesBows
    {
        public static string[] BaseTypes =
        {
            "Crude Bow",
            "Short Bow",
            "Long Bow",
            "Composite Bow",
            "Recurve Bow",
            "Bone Bow",
            "Royal Bow",
            "Death Bow",
            "Grove Bow",
            "Reflex Bow",
            "Decurve Bow",
            "Compound Bow",
            "Sniper Bow",
            "Ivory Bow",
            "Highborn Bow",
            "Decimation Bow",
            "Thicket Bow",
            "Steelwood Bow",
            "Citadel Bow",
            "Ranger Bow",
            "Assassin Bow",
            "Spine Bow",
            "Imperial Bow",
            "Harbinger Bow",
            "Maraketh Bow",
        };
    }

    public static class BaseTypesClaws
    {
        public static string[] BaseTypes =
        {
            "Nailed Fist",
            "Sharktooth Claw",
            "Awl",
            "Cat's Paw",
            "Blinder",
            "Timeworn Claw",
            "Sparkling Claw",
            "Fright Claw",
            "Double Claw",
            "Thresher Claw",
            "Gouger",
            "Tiger's Paw",
            "Gut Ripper",
            "Prehistoric Claw",
            "Noble Claw",
            "Eagle Claw",
            "Twin Claw",
            "Great White Claw",
            "Throat Stabber",
            "Hellion's Paw",
            "Eye Gouger",
            "Vaal Claw",
            "Imperial Claw",
            "Terror Claw",
            "Gemini Claw",
        };
    }

    public static class BaseTypesDaggers
    {
        public static string[] BaseTypes =
        {
            "Glass Shank",
            "Skinning Knife",
            "Carving Knife",
            "Stiletto",
            "Boot Knife",
            "Copper Kris",
            "Skean",
            "Imp Dagger",
            "Flaying Knife",
            "Prong Dagger",
            "Butcher Knife",
            "Poignard",
            "Boot Blade",
            "Golden Kris",
            "Royal Skean",
            "Fiend Dagger",
            "Trisula",
            "Gutting Knife",
            "Slaughter Knife",
            "Ambusher",
            "Ezomyte Dagger",
            "Platinum Kris",
            "Imperial Skean",
            "Demon Dagger",
            "Sai",
        };
    }

    public static class BaseTypesOneHandedAxes
    {
        public static string[] BaseTypes =
        {
            "Rusted Hatchet",
            "Jade Hatchet",
            "Boarding Axe",
            "Cleaver",
            "Broad Axe",
            "Arming Axe",
            "Decorative Axe",
            "Spectral Axe",
            "Etched Hatchet",
            "Jasper Axe",
            "Tomahawk",
            "Wrist Chopper",
            "War Axe",
            "Chest Splitter",
            "Ceremonial Axe",
            "Wraith Axe",
            "Engraved Hatchet",
            "Karui Axe",
            "Siege Axe",
            "Reaver Axe",
            "Butcher Axe",
            "Vaal Hatchet",
            "Royal Axe",
            "Infernal Axe",
            "Runic Hatchet",
        };
    }

    public static class BaseTypesOneHandedMaces
    {
        public static string[] BaseTypes =
        {
            "Driftwood Club",
            "Tribal Club",
            "Spiked Club",
            "Stone Hammer",
            "War Hammer",
            "Bladed Mace",
            "Ceremonial Mace",
            "Dream Mace",
            "Wyrm Mace",
            "Petrified Club",
            "Barbed Club",
            "Rock Breaker",
            "Battle Hammer",
            "Flanged Mace",
            "Ornate Mace",
            "Phantom Mace",
            "Dragon Mace",
            "Ancestral Club",
            "Tenderizer",
            "Gavel",
            "Legion Hammer",
            "Pernarch",
            "Auric Mace",
            "Nightmare Mace",
            "Behemoth Mace",
        };
    }

    public static class BaseTypesOneHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Rusted Sword",
            "Copper Sword",
            "Sabre",
            "Broad Sword",
            "War Sword",
            "Ancient Sword",
            "Elegant Sword",
            "Dusk Blade",
            "Hook Sword",
            "Variscite Blade",
            "Cutlass",
            "Baselard",
            "Battle Sword",
            "Elder Sword",
            "Graceful Sword",
            "Twilight Blade",
            "Grappler",
            "Gemstone Sword",
            "Corsair Sword",
            "Gladius",
            "Legion Sword",
            "Vaal Blade",
            "Eternal Sword",
            "Midnight Blade",
            "Tiger Hook",
        };
    }

    public static class BaseTypesSceptres
    {
        public static string[] BaseTypes =
        {
            "Driftwood Sceptre",
            "Darkwood Sceptre",
            "Bronze Sceptre",
            "Quartz Sceptre",
            "Iron Sceptre",
            "Ochre Sceptre",
            "Ritual Sceptre",
            "Shadow Sceptre",
            "Grinning Fetish",
            "Horned Sceptre",
            "Sekhem",
            "Crystal Sceptre",
            "Lead Sceptre",
            "Blood Sceptre",
            "Royal Sceptre",
            "Abyssal Sceptre",
            "Stag Sceptre",
            "Karui Sceptre",
            "Tyrant's Sekhem",
            "Opal Sceptre",
            "Platinum Sceptre",
            "Vaal Sceptre",
            "Carnal Sceptre",
            "Void Sceptre",
            "Sambar Sceptre",
        };
    }

    public static class BaseTypesStaffs
    {
        public static string[] BaseTypes =
        {
            "Gnarled Branch",
            "Primitive Staff",
            "Long Staff",
            "Iron Staff",
            "Coiled Staff",
            "Royal Staff",
            "Vile Staff",
            "Crescent Staff",
            "Woodful Staff",
            "Quarterstaff",
            "Military Staff",
            "Serpentine Staff",
            "Highborn Staff",
            "Foul Staff",
            "Moon Staff",
            "Primordial Staff",
            "Lathi",
            "Ezomyte Staff",
            "Maelström Staff",
            "Imperial Staff",
            "Judgement Staff",
            "Eclipse Staff",
        };
    }

    public static class BaseTypesThrustingOneHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Rusted Spike",
            "Whalebone Rapier",
            "Battered Foil",
            "Basket Rapier",
            "Jagged Foil",
            "Antique Rapier",
            "Elegant Foil",
            "Thorn Rapier",
            "Smallsword",
            "Wyrmbone Rapier",
            "Burnished Foil",
            "Estoc",
            "Serrated Foil",
            "Primeval Rapier",
            "Fancy Foil",
            "Apex Rapier",
            "Courtesan Sword",
            "Dragonbone Rapier",
            "Tempered Foil",
            "Pecoraro",
            "Spiraled Foil",
            "Vaal Rapier",
            "Jewelled Foil",
            "Harpy Rapier",
            "Dragoon Sword",
        };
    }

    public static class BaseTypesTwoHandedAxes
    {
        public static string[] BaseTypes =
        {
            "Stone Axe",
            "Jade Chopper",
            "Woodsplitter",
            "Poleaxe",
            "Double Axe",
            "Gilded Axe",
            "Shadow Axe",
            "Dagger Axe",
            "Jasper Chopper",
            "Timber Axe",
            "Headsman Axe",
            "Labrys",
            "Noble Axe",
            "Abyssal Axe",
            "Karui Chopper",
            "Talon Axe",
            "Sundering Axe",
            "Ezomyte Axe",
            "Vaal Axe",
            "Despot Axe",
            "Void Axe",
            "Fleshripper",
        };
    }

    public static class BaseTypesTwoHandedMaces
    {
        public static string[] BaseTypes =
        {
            "Driftwood Maul",
            "Tribal Maul",
            "Mallet",
            "Sledgehammer",
            "Jagged Maul",
            "Brass Maul",
            "Fright Maul",
            "Morning Star",
            "Totemic Maul",
            "Great Mallet",
            "Steelhead",
            "Spiny Maul",
            "Plated Maul",
            "Dread Maul",
            "Solar Maul",
            "Karui Maul",
            "Colossus Mallet",
            "Piledriver",
            "Meatgrinder",
            "Imperial Maul",
            "Terror Maul",
            "Coronal Maul",
        };
    }

    public static class BaseTypesTwoHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Corroded Blade",
            "Longsword",
            "Bastard Sword",
            "Two-Handed Sword",
            "Etched Greatsword",
            "Ornate Sword",
            "Spectral Sword",
            "Curved Blade",
            "Butcher Sword",
            "Footman Sword",
            "Highland Blade",
            "Engraved Greatsword",
            "Tiger Sword",
            "Wraith Sword",
            "Lithe Blade",
            "Headman's Sword",
            "Reaver Sword",
            "Ezomyte Blade",
            "Vaal Greatsword",
            "Lion Sword",
            "Infernal Sword",
            "Exquisite Blade",
        };
    }

    public static class BaseTypesWands
    {
        public static string[] BaseTypes =
        {
            "Driftwood Wand",
            "Goat's Horn",
            "Carved Wand",
            "Quartz Wand",
            "Spiraled Wand",
            "Sage Wand",
            "Pagan Wand",
            "Faun's Horn",
            "Engraved Wand",
            "Crystal Wand",
            "Serpent Wand",
            "Omen Wand",
            "Heathen Wand",
            "Demon's Horn",
            "Imbued Wand",
            "Opal Wand",
            "Tornado Wand",
            "Prophecy Wand",
            "Profane Wand",
        };
    }

    public static class BaseTypesJewels
    {
        public static string[] BaseTypes =
        {
            "Cobalt Jewel",
            "Crimson Jewel",
            "Viridian Jewel",
            "Prismatic Jewel",
        };
    }

    public static class BaseTypesMaps
    {
        public static string[] BaseTypes =
        {
            "Arcade Map",
            "Crystal Ore Map",
            "Desert Map",
            "Jungle Valley Map",
            "Beach Map",
            "Factory Map",
            "Ghetto Map",
            "Oasis Map",
            "Arid Lake Map",
            "Cavern Map",
            "Channel Map",
            "Grotto Map",
            "Marshes Map",
            "Sewer Map",
            "Vaal Pyramid Map",
            "Academy Map",
            "Acid Lakes Map",
            "Dungeon Map",
            "Graveyard Map",
            "Phantasmagoria Map",
            "Villa Map",
            "Waste Pool Map",
            "Burial Chambers Map",
            "Dunes Map",
            "Mesa Map",
            "Peninsula Map",
            "Pit Map",
            "Primordial Pool Map",
            "Spider Lair Map",
            "Tower Map",
            "Canyon Map",
            "Quarry Map",
            "Racecourse Map",
            "Ramparts Map",
            "Spider Forest Map",
            "Strand Map",
            "Thicket Map",
            "Vaal City Map",
            "Wharf Map",
            "Arachnid Tomb Map",
            "Armoury Map",
            "Ashen Wood Map",
            "Castle Ruins Map",
            "Catacombs Map",
            "Cells Map",
            "Mud Geyser Map",
            "Arachnid Nest Map",
            "Arena Map",
            "Atoll Map",
            "Barrows Map",
            "Bog Map",
            "Cemetery Map",
            "Pier Map",
            "Shore Map",
            "Tropical Island Map",
            "Coves Map",
            "Crypt Map",
            "Museum Map",
            "Orchard Map",
            "Overgrown Shrine Map",
            "Promenade Map",
            "Reef Map",
            "Temple Map",
            "Arsenal Map",
            "Colonnade Map",
            "Courtyard Map",
            "Malformation Map",
            "Quay Map",
            "Malformation Map",
            "Terrace Map",
            "Underground River Map",
            "Bazaar Map",
            "Chateau Map",
            "Excavation Map",
            "Precinct Map",
            "Torture Chamber Map",
            "Underground Sea Map",
            "Wasteland Map",
            "Crematorium Map",
            "Estuary Map",
            "Ivory Temple Map",
            "Necropolis Map",
            "Plateau Map",
            "Residence Map",
            "Shipyard Map",
            "Vault Map",
            "Beacon Map",
            "Gorge Map",
            "High Gardens Map",
            "Lair Map",
            "Plaza Map",
            "Scriptorium Map",
            "Sulphur Wastes Map",
            "Waterways Map",
            "Maze Map",
            "Mineral Pools Map",
            "Palace Map",
            "Shrine Map",
            "Springs Map",
            "Volcano Map",
            "Abyss Map",
            "Colosseum Map",
            "Core Map",
            "Dark Forest Map",
            "Overgrown Ruin Map",
            "Forge of the Phoenix Map",
            "Lair of the Hydra Map",
            "Maze of the Minotaur Map",
            "Pit of the Chimera Map",
            "Vaal Temple Map",
        };
    }

    public static class BaseTypesMapFragments
    {
        public static string[] BaseTypes =
        {
            "Sacrifice at Dusk",
            "Sacrifice at Midnight",
            "Sacrifice at Dawn",
            "Sacrifice at Noon",
            "Mortal Grief",
            "Mortal Rage",
            "Mortal Hope",
            "Mortal Ignorance",
            "Volkuur's Key",
            "Eber's Key",
            "Yriel's Key",
            "Inya's Key",
            "Fragment of the Hydra",
            "Fragment of the Phoenix",
            "Fragment of the Minotaur",
            "Fragment of the Chimera",
        };
    }

    public static class BaseTypesSkillGems
    {
        public static string[] BaseTypes =
        {
            "Abyssal Cry",
            "Added Chaos Damage Support",
            "Added Cold Damage Support",
            "Added Fire Damage Support",
            "Added Lightning Damage Support",
            "Additional Accuracy Support",
            "Ancestral Protector",
            "Ancestral Warchief",
            "Anger",
            "Animate Guardian",
            "Animate Weapon",
            "Arc",
            "Arctic Armour",
            "Arctic Breath",
            "Assassin's Mark",
            "Ball Lightning",
            "Barrage",
            "Bear Trap",
            "Blade Flurry",
            "Blade Vortex",
            "Bladefall",
            "Blasphemy Support",
            "Blast Rain",
            "Blight",
            "Blind Support",
            "Blink Arrow",
            "Block Chance Reduction Support",
            "Blood Magic Support",
            "Blood Rage",
            "Bloodlust Support",
            "Bone Offering",
            "Burning Arrow",
            "Cast On Critical Strike Support",
            "Cast on Death Support",
            "Cast on Melee Kill Support",
            "Cast when Damage Taken Support",
            "Cast when Stunned Support",
            "Cast while Channelling Support",
            "Caustic Arrow",
            "Chain Support",
            "Chance to Flee Support",
            "Chance to Ignite Support",
            "Clarity",
            "Cleave",
            "Cluster Traps Support",
            "Cold Penetration Support",
            "Cold Snap",
            "Cold to Fire Support",
            "Concentrated Effect Support",
            "Conductivity",
            "Contagion",
            "Controlled Destruction Support",
            "Conversion Trap",
            "Convocation",
            "Culling Strike Support",
            "Curse On Hit Support",
            "Cyclone",
            "Decoy Totem",
            "Desecrate",
            "Determination",
            "Detonate Dead",
            "Detonate Mines",
            "Devouring Totem",
            "Discharge",
            "Discipline",
            "Dominating Blow",
            "Double Strike",
            "Dual Strike",
            "Earthquake",
            "Elemental Focus Support",
            "Elemental Hit",
            "Elemental Proliferation Support",
            "Elemental Weakness",
            "Empower Support",
            "Endurance Charge on Melee Stun Support",
            "Enduring Cry",
            "Enfeeble",
            "Enhance Support",
            "Enlighten Support",
            "Essence Drain",
            "Ethereal Knives",
            "Explosive Arrow",
            "Faster Attacks Support",
            "Faster Casting Support",
            "Faster Projectiles Support",
            "Fire Nova Mine",
            "Fire Penetration Support",
            "Fire Trap",
            "Fireball",
            "Firestorm",
            "Flame Dash",
            "Flame Surge",
            "Flame Totem",
            "Flameblast",
            "Flammability",
            "Flesh Offering",
            "Flicker Strike",
            "Fork Support",
            "Fortify Support",
            "Freeze Mine",
            "Freezing Pulse",
            "Frenzy",
            "Frost Blades",
            "Frost Bomb",
            "Frost Wall",
            "Frostbite",
            "Frostbolt",
            "Generosity Support",
            "Glacial Cascade",
            "Glacial Hammer",
            "Grace",
            "Greater Multiple Projectiles Support",
            "Ground Slam",
            "Haste",
            "Hatred",
            "Heavy Strike",
            "Herald of Ash",
            "Herald of Ice",
            "Herald of Thunder",
            "Hypothermia Support",
            "Ice Bite Support",
            "Ice Crash",
            "Ice Nova",
            "Ice Shot",
            "Ice Spear",
            "Ice Trap",
            "Immortal Call",
            "Incinerate",
            "Increased Area of Effect Support",
            "Increased Burning Damage Support",
            "Increased Critical Damage Support",
            "Increased Critical Strikes Support",
            "Increased Duration Support",
            "Infernal Blow",
            "Innervate Support",
            "Iron Grip Support",
            "Iron Will Support",
            "Item Quantity Support",
            "Item Rarity Support",
            "Kinetic Blast",
            "Knockback Support",
            "Lacerate",
            "Leap Slam",
            "Less Duration Support",
            "Lesser Multiple Projectiles Support",
            "Life Gain on Hit Support",
            "Life Leech Support",
            "Lightning Arrow",
            "Lightning Penetration Support",
            "Lightning Strike",
            "Lightning Tendrils",
            "Lightning Trap",
            "Lightning Warp",
            "Magma Orb",
            "Mana Leech Support",
            "Melee Damage on Full Life Support",
            "Melee Physical Damage Support",
            "Melee Splash Support",
            "Minefield Support",
            "Minion Damage Support",
            "Minion Life Support",
            "Minion Speed Support",
            "Minion and Totem Elemental Resistance Support",
            "Mirror Arrow",
            "Molten Shell",
            "Molten Strike",
            "Multiple Traps Support",
            "Multistrike Support",
            "Orb of Storms",
            "Phase Run",
            "Physical Projectile Attack Damage Support",
            "Physical to Lightning Support",
            "Pierce Support",
            "Poacher's Mark",
            "Point Blank Support",
            "Poison Support",
            "Portal",
            "Power Charge On Critical Support",
            "Power Siphon",
            "Projectile Weakness",
            "Puncture",
            "Punishment",
            "Purity of Elements",
            "Purity of Fire",
            "Purity of Ice",
            "Purity of Lightning",
            "Rain of Arrows",
            "Raise Spectre",
            "Raise Zombie",
            "Rallying Cry",
            "Ranged Attack Totem Support",
            "Rapid Decay Support",
            "Reave",
            "Reckoning",
            "Reduced Mana Support",
            "Rejuvenation Totem",
            "Remote Mine Support",
            "Righteous Fire",
            "Riposte",
            "Scorching Ray",
            "Searing Bond",
            "Shield Charge",
            "Shock Nova",
            "Shockwave Totem",
            "Shrapnel Shot",
            "Siege Ballista",
            "Slower Projectiles Support",
            "Smoke Mine",
            "Spark",
            "Spectral Throw",
            "Spell Echo Support",
            "Spell Totem Support",
            "Spirit Offering",
            "Split Arrow",
            "Static Strike",
            "Storm Call",
            "Stun Support",
            "Summon Chaos Golem",
            "Summon Flame Golem",
            "Summon Ice Golem",
            "Summon Lightning Golem",
            "Summon Raging Spirit",
            "Summon Skeletons",
            "Summon Stone Golem",
            "Sunder",
            "Sweep",
            "Tempest Shield",
            "Temporal Chains",
            "Tornado Shot",
            "Trap Cooldown Support",
            "Trap Support",
            "Trap and Mine Damage Support",
            "Vaal Arc",
            "Vaal Breach",
            "Vaal Burning Arrow",
            "Vaal Clarity",
            "Vaal Cold Snap",
            "Vaal Cyclone",
            "Vaal Detonate Dead",
            "Vaal Discipline",
            "Vaal Double Strike",
            "Vaal Fireball",
            "Vaal Flameblast",
            "Vaal Glacial Hammer",
            "Vaal Grace",
            "Vaal Ground Slam",
            "Vaal Haste",
            "Vaal Ice Nova",
            "Vaal Immortal Call",
            "Vaal Lightning Strike",
            "Vaal Lightning Trap",
            "Vaal Lightning Warp",
            "Vaal Molten Shell",
            "Vaal Power Siphon",
            "Vaal Rain of Arrows",
            "Vaal Reave",
            "Vaal Righteous Fire",
            "Vaal Spark",
            "Vaal Spectral Throw",
            "Vaal Storm Call",
            "Vaal Summon Skeletons",
            "Vengeance",
            "Vigilant Strike",
            "Viper Strike",
            "Vitality",
            "Void Manipulation Support",
            "Vortex",
            "Vulnerability",
            "Warlord's Mark",
            "Weapon Elemental Damage Support",
            "Whirling Blades",
            "Wild Strike",
            "Wither",
            "Wrath",
        };
    }

    public static class BaseTypesDivinationCards
    {
        public static string[] BaseTypes =
        {
            "Abandoned Wealth",
            "The Aesthete",
            "Anarchy's Price",
            "The Arena Champion",
            "The Artist",
            "Assassin's Favour",
            "Audacity",
            "The Avenger",
            "The Battle Born",
            "The Betrayal",
            "Birth of the Three",
            "Blind Venture",
            "The Body",
            "Boundless Realms",
            "Bowyer's Dream",
            "The Brittle Emperor",
            "The Carrion Crow",
            "The Cartographer",
            "The Cataclysm",
            "The Catalyst",
            "The Celestial Justicar",
            "The Chains that Bind",
            "Chaotic Disposition",
            "The Conduit",
            "Coveted Possession",
            "The Dapper Prodigy",
            "The Dark Mage",
            "Death",
            "The Demoness",
            "Destined to Crumble",
            "The Devastator",
            "The Doctor",
            "Doedre's Madness",
            "The Doppelganger",
            "The Dragon",
            "The Dragon's Heart",
            "The Drunken Aristocrat",
            "Dying Anguish",
            "Earth Drinker",
            "Emperor's Luck",
            "The Encroaching Darkness",
            "The Enlightened",
            "The Ethereal",
            "The Explorer",
            "The Feast",
            "The Fiend",
            "The Fletcher",
            "The Flora's Gift",
            "The Fox",
            "The Gambler",
            "The Gemcutter",
            "Gemcutter's Promise",
            "The Gentleman",
            "Gift of the Gemling Queen",
            "The Gladiator",
            "Glimmer of Hope",
            "Grave Knowledge",
            "Her Mask",
            "The Hermit",
            "Heterochromia",
            "The Hoarder",
            "Hope",
            "House of Mirrors",
            "Hubris",
            "Humility",
            "The Hunger",
            "Hunter's Resolve",
            "Hunter's Reward",
            "The Immortal",
            "The Incantation",
            "The Inoculated",
            "The Inventor",
            "Jack in the Box",
            "The King's Blade",
            "The King's Heart",
            "Lantador's Lost Love",
            "Last Hope",
            "The Last One Standing",
            "The Lich",
            "The Lion",
            "The Lord in Black",
            "Lost Worlds",
            "The Lover",
            "Loyalty",
            "Lucky Connections",
            "The Mercenary",
            "Merciless Armament",
            "The Metalsmith's Gift",
            "A Mother's Parting Gift",
            "The Offering",
            "The One With All",
            "The Pack Leader",
            "The Pact",
            "The Poet",
            "Pride Before the Fall",
            "Prosperity",
            "The Queen",
            "The Rabid Rhoa",
            "Rain of Chaos",
            "Rats",
            "The Risk",
            "The Road to Power",
            "The Scarred Meadow",
            "The Scholar",
            "Scholar of the Seas",
            "Shard of Fate",
            "The Sigil",
            "The Siren",
            "The Spoiled Prince",
            "The Summoner",
            "The Sun",
            "The Surgeon",
            "The Surveyor",
            "The Survivalist",
            "The Thaumaturgist",
            "Three Faces in the Dark",
            "The Throne",
            "Time-Lost Relic",
            "The Tower",
            "The Traitor",
            "Thunderous Skies",
            "Tranquillity",
            "Treasure Hunter",
            "The Trial",
            "Turn the Other Cheek",
            "The Twins",
            "The Union",
            "The Vast",
            "Vinia's Token",
            "The Void",
            "Volatile Power",
            "The Warden",
            "The Warlord",
            "The Watcher",
            "Wealth and Power",
            "The Wind",
            "The Wolf's Shadow",
            "The Wrath",
        };
    }

    public static class BaseTypesFlasks
    {
        public static string[] BaseTypes =
        {
            "Small Life Flask",
            "Medium Life Flask",
            "Large Life Flask",
            "Greater Life Flask",
            "Grand Life Flask",
            "Giant Life Flask",
            "Colossal Life Flask",
            "Sacred Life Flask",
            "Hallowed Life Flask",
            "Sanctified Life Flask",
            "Divine Life Flask",
            "Eternal Life Flask",
            "Small Mana Flask",
            "Medium Mana Flask",
            "Large Mana Flask",
            "Greater Mana Flask",
            "Grand Mana Flask",
            "Giant Mana Flask",
            "Colossal Mana Flask",
            "Sacred Mana Flask",
            "Hallowed Mana Flask",
            "Sanctified Mana Flask",
            "Divine Mana Flask",
            "Eternal Mana Flask",
            "Small Hybrid Flask",
            "Medium Hybrid Flask",
            "Large Hybrid Flask",
            "Colossal Hybrid Flask",
            "Sacred Hybrid Flask",
            "Hallowed Hybrid Flask",
            "Quicksilver Flask",
            "Bismuth Flask",
            "Stibnite Flask",
            "Amethyst Flask",
            "Ruby Flask",
            "Sapphire Flask",
            "Topaz Flask",
            "Silver Flask",
            "Aquamarine Flask",
            "Granite Flask",
            "Jade Flask",
            "Quartz Flask",
            "Sulphur Flask",
            "Basalt Flask",
            "Diamond Flask",
        };
    }

    public static class BaseTypesCurrencies
    {
        public static string[] BaseTypes =
        {
            "Albino Rhoa Feather",
            "Apprentice Cartographer's Seal",
            "Apprentice Cartographer's Sextant",
            "Armourer's Scrap",
            "Blacksmith's Whetstone",
            "Blessed Orb",
            "Blessing of Chayula",
            "Blessing of Esh",
            "Blessing of Tul",
            "Blessing of Uul-Netol",
            "Blessing of Xoph",
            "Cartographer's Chisel",
            "Chaos Orb",
            "Chromatic Orb",
            "Divine Orb",
            "Exalted Orb",
            "Gemcutter's Prism",
            "Glassblower's Bauble",
            "Jeweller's Orb",
            "Journeyman Cartographer's Seal",
            "Journeyman Cartographer's Sextant",
            "Master Cartographer's Seal",
            "Master Cartographer's Sextant",
            "Mirror of Kalandra",
            "Orb of Alchemy",
            "Orb of Alteration",
            "Orb of Augmentation",
            "Orb of Chance",
            "Orb of Fusing",
            "Orb of Regret",
            "Orb of Scouring",
            "Orb of Transmutation",
            "Perandus Coin",
            "Portal Scroll",
            "Prophecy",
            "Regal Orb",
            "Scroll of Wisdom",
            "Silver Coin",
            "Stacked Deck",
            "Unshaping Orb",
            "Vaal Orb",
            "Alchemy Shard",
            "Alteration Shard",
            "Scroll Fragment",
            "Splinter of Chayula",
            "Splinter of Esh",
            "Splinter of Tul",
            "Splinter of Uul-Netol",
            "Splinter of Xoph",
            "Transmutation Shard",
        };
    }

    public static class Uniques
    {
        public static Unique[] AllUniques =
        {
            new Unique(ItemType.Amulet, "Araku Tiki"),
            new Unique(ItemType.Amulet, "Sidhebreath"),
            new Unique(ItemType.Amulet, "Karui Ward"),
            new Unique(ItemType.Amulet, "Stone of Lazhwar"),
            new Unique(ItemType.Amulet, "The Ascetic"),
            new Unique(ItemType.Amulet, "The Ignomon"),
            new Unique(ItemType.Amulet, "Atziri's Foible"),
            new Unique(ItemType.Amulet, "Daresso's Salute"),
            new Unique(ItemType.Amulet, "Extractor Mentis"),
            new Unique(ItemType.Amulet, "Shaper's Seed"),
            new Unique(ItemType.Amulet, "Victario's Acuity"),
            new Unique(ItemType.Amulet, "Astramentis"),
            new Unique(ItemType.Amulet, "Blood of Corruption"),
            new Unique(ItemType.Amulet, "Carnage Heart"),
            new Unique(ItemType.Amulet, "Eye of Chayula"),
            new Unique(ItemType.Amulet, "Hinekora's Sight"),
            new Unique(ItemType.Amulet, "Tear of Purity"),
            new Unique(ItemType.Amulet, "Ungil's Harmony"),
            new Unique(ItemType.Amulet, "Karui Charge"),
            new Unique(ItemType.Amulet, "Night's Hold"),
            new Unique(ItemType.Amulet, "Blightwell"),
            new Unique(ItemType.Amulet, "Rigwald's Curse"),
            new Unique(ItemType.Amulet, "Bisco's Collar"),
            new Unique(ItemType.Amulet, "The Aylardex"),
            new Unique(ItemType.Amulet, "Voll's Devotion"),
            new Unique(ItemType.Amulet, "The Halcyon"),
            new Unique(ItemType.Amulet, "Xoph's Heart"),
            new Unique(ItemType.Amulet, "Ngamahu Tiki"),
            new Unique(ItemType.Amulet, "Marylene's Fallacy"),
            new Unique(ItemType.Amulet, "Voice of the Storm"),
            new Unique(ItemType.Amulet, "Winterheart"),
            new Unique(ItemType.Amulet, "Natural Hierarchy"),
            new Unique(ItemType.Amulet, "The Anvil"),
            new Unique(ItemType.Amulet, "Warped Timepiece"),
            new Unique(ItemType.Amulet, "Eyes of the Greatwolf"),
            new Unique(ItemType.Amulet, "Bloodgrip"),
            new Unique(ItemType.Amulet, "Presence of Chayula"),
            new Unique(ItemType.Amulet, "Rashkaldor's Patience"),
            new Unique(ItemType.Amulet, "The Pandemonius"),
            new Unique(ItemType.Amulet, "Xoph's Blood"),
            new Unique(ItemType.Amulet, "Eye of Innocence"),
            new Unique(ItemType.Amulet, "Choir of the Storm"),
            new Unique(ItemType.Belt, "Belt of the Deceiver"),
            new Unique(ItemType.Belt, "Meginord's Girdle"),
            new Unique(ItemType.Belt, "Wurm's Molt"),
            new Unique(ItemType.Belt, "Feastbind"),
            new Unique(ItemType.Belt, "Perandus Blazon"),
            new Unique(ItemType.Belt, "The Magnate"),
            new Unique(ItemType.Belt, "Faminebind"),
            new Unique(ItemType.Belt, "Bated Breath"),
            new Unique(ItemType.Belt, "Prismweave"),
            new Unique(ItemType.Belt, "Bisco's Leash"),
            new Unique(ItemType.Belt, "Umbilicus Immortalis"),
            new Unique(ItemType.Belt, "Ryslatha's Coil"),
            new Unique(ItemType.Belt, "Sunblast"),
            new Unique(ItemType.Belt, "Headhunter"),
            new Unique(ItemType.Belt, "Ascent From Flesh"),
            new Unique(ItemType.Belt, "Maligaro's Restraint"),
            new Unique(ItemType.Belt, "The Retch"),
            new Unique(ItemType.Belt, "Soulthirst"),
            new Unique(ItemType.Belt, "Immortal Flesh"),
            new Unique(ItemType.Belt, "Dyadian Dawn"),
            new Unique(ItemType.Belt, "Doryani's Invitation"),
            new Unique(ItemType.Belt, "Perseverance"),
            new Unique(ItemType.Belt, "Auxium"),
            new Unique(ItemType.Ring, "Blackheart"),
            new Unique(ItemType.Ring, "Doedre's Damning"),
            new Unique(ItemType.Ring, "Kaom's Sign"),
            new Unique(ItemType.Ring, "Perandus Signet"),
            new Unique(ItemType.Ring, "Malachai's Artifice"),
            new Unique(ItemType.Ring, "Pyre"),
            new Unique(ItemType.Ring, "Emberwake"),
            new Unique(ItemType.Ring, "Mokou's Embrace"),
            new Unique(ItemType.Ring, "Andvarius"),
            new Unique(ItemType.Ring, "Berek's Grip"),
            new Unique(ItemType.Ring, "Berek's Pass"),
            new Unique(ItemType.Ring, "Berek's Respite"),
            new Unique(ItemType.Ring, "Call of the Brotherhood"),
            new Unique(ItemType.Ring, "Heartbound Loop"),
            new Unique(ItemType.Ring, "Kikazaru"),
            new Unique(ItemType.Ring, "Tasalio's Sign"),
            new Unique(ItemType.Ring, "Praxis"),
            new Unique(ItemType.Ring, "Timeclasp"),
            new Unique(ItemType.Ring, "Bloodboil"),
            new Unique(ItemType.Ring, "Dream Fragments"),
            new Unique(ItemType.Ring, "Le Heup of All"),
            new Unique(ItemType.Ring, "Gifts from Above"),
            new Unique(ItemType.Ring, "Ngamahu's Sign"),
            new Unique(ItemType.Ring, "Lori's Lantern"),
            new Unique(ItemType.Ring, "Shavronne's Revelation"),
            new Unique(ItemType.Ring, "The Taming"),
            new Unique(ItemType.Ring, "The Warden's Brand"),
            new Unique(ItemType.Ring, "Thief's Torment"),
            new Unique(ItemType.Ring, "Kaom's Way"),
            new Unique(ItemType.Ring, "Angler's Plait"),
            new Unique(ItemType.Ring, "Essence Worm"),
            new Unique(ItemType.Ring, "Valako's Sign"),
            new Unique(ItemType.Ring, "Valyrium"),
            new Unique(ItemType.Ring, "Brinerot Mark"),
            new Unique(ItemType.Ring, "Mutewind Seal"),
            new Unique(ItemType.Ring, "Redblade Band"),
            new Unique(ItemType.Ring, "Sibyl's Lament"),
            new Unique(ItemType.Ring, "Voideye"),
            new Unique(ItemType.Ring, "Death Rush"),
            new Unique(ItemType.Ring, "Voidheart"),
            new Unique(ItemType.Ring, "Rigwald's Crest"),
            new Unique(ItemType.Ring, "Romira's Banquet"),
            new Unique(ItemType.Ring, "The Pariah"),
            new Unique(ItemType.Ring, "Ventor's Gamble"),
            new Unique(ItemType.Ring, "Snakepit"),
            new Unique(ItemType.Ring, "Ming's Heart"),
            new Unique(ItemType.Quiver, "Cragfall"),
            new Unique(ItemType.Quiver, "Craghead"),
            new Unique(ItemType.Quiver, "Asphyxia's Wrath"),
            new Unique(ItemType.Quiver, "Hyrri's Bite"),
            new Unique(ItemType.Quiver, "Skirmish"),
            new Unique(ItemType.Quiver, "Blackgleam"),
            new Unique(ItemType.Quiver, "The Signal Fire"),
            new Unique(ItemType.Quiver, "Rearguard"),
            new Unique(ItemType.Quiver, "Drillneck"),
            new Unique(ItemType.Quiver, "Saemus' Gift"),
            new Unique(ItemType.Quiver, "Maloney's Nightfall"),
            new Unique(ItemType.Quiver, "Rigwald's Quills"),
            new Unique(ItemType.Quiver, "Soul Strike"),
            new Unique(ItemType.Quiver, "Broadstroke"),
            new Unique(ItemType.BodyArmour, "Bramblejack"),
            new Unique(ItemType.BodyArmour, "Solaris Lorica"),
            new Unique(ItemType.BodyArmour, "Wall of Brambles"),
            new Unique(ItemType.BodyArmour, "Greed's Embrace"),
            new Unique(ItemType.BodyArmour, "Lioneye's Vision"),
            new Unique(ItemType.BodyArmour, "Death's Oath"),
            new Unique(ItemType.BodyArmour, "The Brass Dome"),
            new Unique(ItemType.BodyArmour, "Kaom's Heart"),
            new Unique(ItemType.BodyArmour, "Briskwrap"),
            new Unique(ItemType.BodyArmour, "Ashrend"),
            new Unique(ItemType.BodyArmour, "Foxshade"),
            new Unique(ItemType.BodyArmour, "The Snowblind Grace"),
            new Unique(ItemType.BodyArmour, "Bronn's Lithe"),
            new Unique(ItemType.BodyArmour, "The Rat Cage"),
            new Unique(ItemType.BodyArmour, "Queen of the Forest"),
            new Unique(ItemType.BodyArmour, "Kintsugi"),
            new Unique(ItemType.BodyArmour, "The Perfect Form"),
            new Unique(ItemType.BodyArmour, "Hyrri's Ire"),
            new Unique(ItemType.BodyArmour, "Cospri's Will"),
            new Unique(ItemType.BodyArmour, "Skin of the Loyal"),
            new Unique(ItemType.BodyArmour, "Tabula Rasa"),
            new Unique(ItemType.BodyArmour, "Thousand Ribbons"),
            new Unique(ItemType.BodyArmour, "Skin of the Lords"),
            new Unique(ItemType.BodyArmour, "Cloak of Flame"),
            new Unique(ItemType.BodyArmour, "Zahndethus' Cassock"),
            new Unique(ItemType.BodyArmour, "Soul Mantle"),
            new Unique(ItemType.BodyArmour, "The Covenant"),
            new Unique(ItemType.BodyArmour, "Cloak of Tawm'r Isley"),
            new Unique(ItemType.BodyArmour, "Vis Mortis"),
            new Unique(ItemType.BodyArmour, "Shavronne's Wrappings"),
            new Unique(ItemType.BodyArmour, "Infernal Mantle"),
            new Unique(ItemType.BodyArmour, "The Beast Fur Shawl"),
            new Unique(ItemType.BodyArmour, "Viper's Scales"),
            new Unique(ItemType.BodyArmour, "Gruthkul's Pelt"),
            new Unique(ItemType.BodyArmour, "Belly of the Beast"),
            new Unique(ItemType.BodyArmour, "Lightning Coil"),
            new Unique(ItemType.BodyArmour, "Daresso's Defiance"),
            new Unique(ItemType.BodyArmour, "Cherrubim's Maleficence"),
            new Unique(ItemType.BodyArmour, "Voll's Protector"),
            new Unique(ItemType.BodyArmour, "Icetomb"),
            new Unique(ItemType.BodyArmour, "Ambu's Charge"),
            new Unique(ItemType.BodyArmour, "Lightbane Raiment"),
            new Unique(ItemType.BodyArmour, "Kingsguard"),
            new Unique(ItemType.BodyArmour, "Geofri's Sanctuary"),
            new Unique(ItemType.BodyArmour, "Incandescent Heart"),
            new Unique(ItemType.BodyArmour, "Cloak of Defiance"),
            new Unique(ItemType.BodyArmour, "Victario's Influence"),
            new Unique(ItemType.BodyArmour, "Carcass Jack"),
            new Unique(ItemType.BodyArmour, "The Restless Ward"),
            new Unique(ItemType.BodyArmour, "Demigod's Dominance"),
            new Unique(ItemType.BodyArmour, "Atziri's Splendour"),
            new Unique(ItemType.Boots, "Windscream"),
            new Unique(ItemType.Boots, "Redblade Tramplers"),
            new Unique(ItemType.Boots, "The Infinite Pursuit"),
            new Unique(ItemType.Boots, "Kaom's Roots"),
            new Unique(ItemType.Boots, "The Red Trail"),
            new Unique(ItemType.Boots, "Seven-League Step"),
            new Unique(ItemType.Boots, "Abberath's Hooves"),
            new Unique(ItemType.Boots, "Victario's Flight"),
            new Unique(ItemType.Boots, "Deerstalker"),
            new Unique(ItemType.Boots, "Goldwyrm"),
            new Unique(ItemType.Boots, "The Blood Dance"),
            new Unique(ItemType.Boots, "Three-step Assault"),
            new Unique(ItemType.Boots, "Garukhan's Flight"),
            new Unique(ItemType.Boots, "Sin Trek"),
            new Unique(ItemType.Boots, "Atziri's Step"),
            new Unique(ItemType.Boots, "Wanderlust"),
            new Unique(ItemType.Boots, "Wondertrap"),
            new Unique(ItemType.Boots, "Bones of Ullr"),
            new Unique(ItemType.Boots, "Shavronne's Gambit"),
            new Unique(ItemType.Boots, "Shavronne's Pace"),
            new Unique(ItemType.Boots, "Rainbowstride"),
            new Unique(ItemType.Boots, "Skyforth"),
            new Unique(ItemType.Boots, "Steppan Eard"),
            new Unique(ItemType.Boots, "Dusktoe"),
            new Unique(ItemType.Boots, "Lioneye's Paws"),
            new Unique(ItemType.Boots, "Mutewind Whispersteps"),
            new Unique(ItemType.Boots, "Darkray Vectors"),
            new Unique(ItemType.Boots, "Wake of Destruction"),
            new Unique(ItemType.Boots, "Alberon's Warpath"),
            new Unique(ItemType.Boots, "Gang's Momentum"),
            new Unique(ItemType.Boots, "Death's Door"),
            new Unique(ItemType.Boots, "Nomic's Storm"),
            new Unique(ItemType.Boots, "Sundance"),
            new Unique(ItemType.Boots, "Brinerot Whalers"),
            new Unique(ItemType.Boots, "Voidwalker"),
            new Unique(ItemType.Boots, "Demigod's Stride"),
            new Unique(ItemType.Gloves, "Lochtonial Caress"),
            new Unique(ItemType.Gloves, "Meginord's Vise"),
            new Unique(ItemType.Gloves, "Winds of Change"),
            new Unique(ItemType.Gloves, "Empire's Grasp"),
            new Unique(ItemType.Gloves, "Doryani's Fist"),
            new Unique(ItemType.Gloves, "Veruso's Battering Rams"),
            new Unique(ItemType.Gloves, "Atziri's Acuity"),
            new Unique(ItemType.Gloves, "Hrimsorrow"),
            new Unique(ItemType.Gloves, "Maligaro's Virtuosity"),
            new Unique(ItemType.Gloves, "Hrimburn"),
            new Unique(ItemType.Gloves, "Sadima's Touch"),
            new Unique(ItemType.Gloves, "Doedre's Tenure"),
            new Unique(ItemType.Gloves, "Asenath's Gentle Touch"),
            new Unique(ItemType.Gloves, "Voidbringer"),
            new Unique(ItemType.Gloves, "Grip of the Council"),
            new Unique(ItemType.Gloves, "Flesh and Spirit"),
            new Unique(ItemType.Gloves, "Slitherpinch"),
            new Unique(ItemType.Gloves, "Vaal Caress"),
            new Unique(ItemType.Gloves, "Aurseize"),
            new Unique(ItemType.Gloves, "Haemophilia"),
            new Unique(ItemType.Gloves, "Wyrmsign"),
            new Unique(ItemType.Gloves, "Surgebinders"),
            new Unique(ItemType.Gloves, "Shackles of the Wretched"),
            new Unique(ItemType.Gloves, "Southbound"),
            new Unique(ItemType.Gloves, "Null and Void"),
            new Unique(ItemType.Gloves, "Repentance"),
            new Unique(ItemType.Gloves, "Shaper's Touch"),
            new Unique(ItemType.Gloves, "Ondar's Clasp"),
            new Unique(ItemType.Gloves, "Facebreaker"),
            new Unique(ItemType.Gloves, "Shadows and Dust"),
            new Unique(ItemType.Gloves, "Snakebite"),
            new Unique(ItemType.Gloves, "Thunderfist"),
            new Unique(ItemType.Gloves, "Demigod's Touch"),
            new Unique(ItemType.Helmet, "Ezomyte Peak"),
            new Unique(ItemType.Helmet, "Ezomyte Hold"),
            new Unique(ItemType.Helmet, "Tear of Entropy"),
            new Unique(ItemType.Helmet, "The Baron"),
            new Unique(ItemType.Helmet, "The Formless Flame"),
            new Unique(ItemType.Helmet, "Hrimnor's Resolve"),
            new Unique(ItemType.Helmet, "Abyssus"),
            new Unique(ItemType.Helmet, "The Formless Inferno"),
            new Unique(ItemType.Helmet, "Goldrim"),
            new Unique(ItemType.Helmet, "Fairgraves' Tricorne"),
            new Unique(ItemType.Helmet, "Heatshiver"),
            new Unique(ItemType.Helmet, "Rat's Nest"),
            new Unique(ItemType.Helmet, "Starkonja's Head"),
            new Unique(ItemType.Helmet, "Alpha's Howl"),
            new Unique(ItemType.Helmet, "Obscurantis"),
            new Unique(ItemType.Helmet, "Crown of Thorns"),
            new Unique(ItemType.Helmet, "Asenath's Mark"),
            new Unique(ItemType.Helmet, "Doedre's Scorn"),
            new Unique(ItemType.Helmet, "Martyr's Crown"),
            new Unique(ItemType.Helmet, "Chitus' Apex"),
            new Unique(ItemType.Helmet, "Rime Gaze"),
            new Unique(ItemType.Helmet, "Scold's Bridle"),
            new Unique(ItemType.Helmet, "Crown of Eyes"),
            new Unique(ItemType.Helmet, "Ylfeban's Trickery"),
            new Unique(ItemType.Helmet, "The Peregrine"),
            new Unique(ItemType.Helmet, "Deidbell"),
            new Unique(ItemType.Helmet, "Deidbellow"),
            new Unique(ItemType.Helmet, "Skullhead"),
            new Unique(ItemType.Helmet, "Black Sun Crest"),
            new Unique(ItemType.Helmet, "The Bringer of Rain"),
            new Unique(ItemType.Helmet, "Devoto's Devotion"),
            new Unique(ItemType.Helmet, "Honourhome"),
            new Unique(ItemType.Helmet, "Veil of the Night"),
            new Unique(ItemType.Helmet, "Mindspiral"),
            new Unique(ItemType.Helmet, "Kitava's Thirst"),
            new Unique(ItemType.Helmet, "Geofri's Crest"),
            new Unique(ItemType.Helmet, "The Broken Crown"),
            new Unique(ItemType.Helmet, "The Brine Crown"),
            new Unique(ItemType.Helmet, "Voll's Vision"),
            new Unique(ItemType.Helmet, "Malachai's Vision"),
            new Unique(ItemType.Helmet, "Malachai's Simula"),
            new Unique(ItemType.Helmet, "Leer Cast"),
            new Unique(ItemType.Helmet, "The Three Dragons"),
            new Unique(ItemType.Helmet, "The Gull"),
            new Unique(ItemType.Helmet, "Crown of the Pale King"),
            new Unique(ItemType.Helmet, "Mind of the Council"),
            new Unique(ItemType.Helmet, "The Vertex"),
            new Unique(ItemType.Helmet, "Heretic's Veil"),
            new Unique(ItemType.Helmet, "Demigod's Triumph"),
            new Unique(ItemType.Shield, "Lycosidae"),
            new Unique(ItemType.Shield, "Trolltimber Spire"),
            new Unique(ItemType.Shield, "Titucius' Span"),
            new Unique(ItemType.Shield, "Redblade Banner"),
            new Unique(ItemType.Shield, "Chernobog's Pillar"),
            new Unique(ItemType.Shield, "Tukohama's Fortress"),
            new Unique(ItemType.Shield, "The Surrender"),
            new Unique(ItemType.Shield, "The Anticipation"),
            new Unique(ItemType.Shield, "Ahn's Heritage"),
            new Unique(ItemType.Shield, "Lioneye's Remorse"),
            new Unique(ItemType.Shield, "Remnant of Empires"),
            new Unique(ItemType.Shield, "Crest of Perandus"),
            new Unique(ItemType.Shield, "Kaltenhalt"),
            new Unique(ItemType.Shield, "Kaltensoul"),
            new Unique(ItemType.Shield, "Chalice of Horrors"),
            new Unique(ItemType.Shield, "Thirst for Horrors"),
            new Unique(ItemType.Shield, "Mutewind Pennant"),
            new Unique(ItemType.Shield, "Great Old One's Ward"),
            new Unique(ItemType.Shield, "Atziri's Mirror"),
            new Unique(ItemType.Shield, "Thousand Teeth Temu"),
            new Unique(ItemType.Shield, "Matua Tupuna"),
            new Unique(ItemType.Shield, "Brinerot Flag"),
            new Unique(ItemType.Shield, "Light of Lunaris"),
            new Unique(ItemType.Shield, "Sentari's Answer"),
            new Unique(ItemType.Shield, "Kongming's Stratagem"),
            new Unique(ItemType.Shield, "Esh's Mirror"),
            new Unique(ItemType.Shield, "Esh's Visage"),
            new Unique(ItemType.Shield, "Malachai's Loop"),
            new Unique(ItemType.Shield, "Rathpith Globe"),
            new Unique(ItemType.Shield, "Wheel of the Stormsail"),
            new Unique(ItemType.Shield, "The Deep One's Hide"),
            new Unique(ItemType.Shield, "Daresso's Courage"),
            new Unique(ItemType.Shield, "Springleaf"),
            new Unique(ItemType.Shield, "The Oak"),
            new Unique(ItemType.Shield, "Victario's Charity"),
            new Unique(ItemType.Shield, "Saffell's Frame"),
            new Unique(ItemType.Shield, "Aegis Aurora"),
            new Unique(ItemType.Shield, "Rise of the Phoenix"),
            new Unique(ItemType.Shield, "Prism Guardian"),
            new Unique(ItemType.Shield, "Broken Faith"),
            new Unique(ItemType.Shield, "Glitterdisc"),
            new Unique(ItemType.Shield, "Maligaro's Lens"),
            new Unique(ItemType.Shield, "Jaws of Agony"),
            new Unique(ItemType.Bow, "Silverbranch"),
            new Unique(ItemType.Bow, "Quill Rain"),
            new Unique(ItemType.Bow, "Storm Cloud"),
            new Unique(ItemType.Bow, "Roth's Reach"),
            new Unique(ItemType.Bow, "Xoph's Inception"),
            new Unique(ItemType.Bow, "Doomfletch"),
            new Unique(ItemType.Bow, "Death's Harp"),
            new Unique(ItemType.Bow, "Iron Commander"),
            new Unique(ItemType.Bow, "The Tempest"),
            new Unique(ItemType.Bow, "Silverbough"),
            new Unique(ItemType.Bow, "Doomfletch's Prism"),
            new Unique(ItemType.Bow, "Death's Opus"),
            new Unique(ItemType.Bow, "Infractem"),
            new Unique(ItemType.Bow, "Null's Inclination"),
            new Unique(ItemType.Bow, "Chin Sol"),
            new Unique(ItemType.Bow, "Darkscorn"),
            new Unique(ItemType.Bow, "Reach of the Council"),
            new Unique(ItemType.Bow, "Voltaxic Rift"),
            new Unique(ItemType.Bow, "Xoph's Nurture"),
            new Unique(ItemType.Bow, "Lioneye's Glare"),
            new Unique(ItemType.Bow, "Windripper"),
            new Unique(ItemType.Bow, "Nuro's Harp"),
            new Unique(ItemType.Bow, "Slivertongue"),
            new Unique(ItemType.Claw, "Last Resort"),
            new Unique(ItemType.Claw, "Wildslash"),
            new Unique(ItemType.Claw, "Hand of Thought and Motion"),
            new Unique(ItemType.Claw, "Al Dhih"),
            new Unique(ItemType.Claw, "Mortem Morsu"),
            new Unique(ItemType.Claw, "Cybil's Paw"),
            new Unique(ItemType.Claw, "Advancing Fortress"),
            new Unique(ItemType.Claw, "Ornament of the East"),
            new Unique(ItemType.Claw, "Bloodseeker"),
            new Unique(ItemType.Claw, "Allure"),
            new Unique(ItemType.Claw, "Essentia Sanguis"),
            new Unique(ItemType.Claw, "Hand of Wisdom and Action"),
            new Unique(ItemType.Claw, "Izaro's Dilemma"),
            new Unique(ItemType.Claw, "Touch of Anguish"),
            new Unique(ItemType.Claw, "Rive"),
            new Unique(ItemType.Claw, "The Scourge"),
            new Unique(ItemType.Dagger, "Goredrill"),
            new Unique(ItemType.Dagger, "Bloodplay"),
            new Unique(ItemType.Dagger, "Ungil's Gauche"),
            new Unique(ItemType.Dagger, "Mightflay"),
            new Unique(ItemType.Dagger, "Widowmaker"),
            new Unique(ItemType.Dagger, "Heartbreaker"),
            new Unique(ItemType.Dagger, "Arakaali's Fang"),
            new Unique(ItemType.Dagger, "The Consuming Dark"),
            new Unique(ItemType.Dagger, "Mark of the Doubting Knight"),
            new Unique(ItemType.Dagger, "Bino's Kitchen Knife"),
            new Unique(ItemType.Dagger, "Divinarius"),
            new Unique(ItemType.Wand, "Lifesprig"),
            new Unique(ItemType.Wand, "Abberath's Horn"),
            new Unique(ItemType.Wand, "Storm Prison"),
            new Unique(ItemType.Wand, "Ashcaller"),
            new Unique(ItemType.Wand, "Reverberation Rod"),
            new Unique(ItemType.Wand, "Tulborn"),
            new Unique(ItemType.Wand, "Shade of Solaris"),
            new Unique(ItemType.Wand, "Twyzel"),
            new Unique(ItemType.Wand, "Amplification Rod"),
            new Unique(ItemType.Wand, "Midnight Bargain"),
            new Unique(ItemType.Wand, "Eclipse Solaris"),
            new Unique(ItemType.Wand, "Obliteration"),
            new Unique(ItemType.Wand, "Moonsorrow"),
            new Unique(ItemType.Wand, "Apep's Rage"),
            new Unique(ItemType.Wand, "Piscator's Vigil"),
            new Unique(ItemType.Wand, "Tulfall"),
            new Unique(ItemType.Wand, "Void Battery"),
            new Unique(ItemType.Staff, "Fencoil"),
            new Unique(ItemType.Staff, "The Blood Thorn"),
            new Unique(ItemType.Staff, "Pillar of the Caged God"),
            new Unique(ItemType.Staff, "Dying Breath"),
            new Unique(ItemType.Staff, "Realmshaper"),
            new Unique(ItemType.Staff, "The Stormheart"),
            new Unique(ItemType.Staff, "Xirgil's Crank"),
            new Unique(ItemType.Staff, "The Whispering Ice"),
            new Unique(ItemType.Staff, "Realm Ender"),
            new Unique(ItemType.Staff, "Tremor Rod"),
            new Unique(ItemType.Staff, "Sire of Shards"),
            new Unique(ItemType.Staff, "Martyr of Innocence"),
            new Unique(ItemType.Staff, "Femurs of the Saints"),
            new Unique(ItemType.Staff, "The Searing Touch"),
            new Unique(ItemType.Staff, "Duskdawn"),
            new Unique(ItemType.Staff, "Taryn's Shiver"),
            new Unique(ItemType.Staff, "Agnerod East"),
            new Unique(ItemType.Staff, "Agnerod North"),
            new Unique(ItemType.Staff, "Agnerod South"),
            new Unique(ItemType.Staff, "Agnerod West"),
            new Unique(ItemType.Staff, "Hegemony's Era"),
            new Unique(ItemType.Staff, "Pledge of Hands"),
            new Unique(ItemType.OneHandedAxe, "The Screaming Eagle"),
            new Unique(ItemType.OneHandedAxe, "Dreadarc"),
            new Unique(ItemType.OneHandedAxe, "Relentless Fury"),
            new Unique(ItemType.OneHandedAxe, "The Gryphon"),
            new Unique(ItemType.OneHandedAxe, "Moonbender's Wing"),
            new Unique(ItemType.OneHandedAxe, "Soul Taker"),
            new Unique(ItemType.OneHandedAxe, "Jack, the Axe"),
            new Unique(ItemType.OneHandedAxe, "Rigwald's Savagery"),
            new Unique(ItemType.OneHandedAxe, "Dyadus"),
            new Unique(ItemType.TwoHandedAxe, "Limbsplit"),
            new Unique(ItemType.TwoHandedAxe, "Wideswing"),
            new Unique(ItemType.TwoHandedAxe, "Reaper's Pursuit"),
            new Unique(ItemType.TwoHandedAxe, "The Harvest"),
            new Unique(ItemType.TwoHandedAxe, "The Cauteriser"),
            new Unique(ItemType.TwoHandedAxe, "The Blood Reaper"),
            new Unique(ItemType.TwoHandedAxe, "Uul-Netol's Kiss"),
            new Unique(ItemType.TwoHandedAxe, "Ngamahu's Flame"),
            new Unique(ItemType.TwoHandedAxe, "Kaom's Primacy"),
            new Unique(ItemType.TwoHandedAxe, "Wings of Entropy"),
            new Unique(ItemType.TwoHandedAxe, "Hezmana's Bloodlust"),
            new Unique(ItemType.TwoHandedAxe, "Uul-Netol's Embrace"),
            new Unique(ItemType.TwoHandedAxe, "Kingmaker"),
            new Unique(ItemType.TwoHandedAxe, "Kitava's Feast"),
            new Unique(ItemType.TwoHandedAxe, "Atziri's Disfavour"),
            new Unique(ItemType.OneHandedMace, "Gorebreaker"),
            new Unique(ItemType.OneHandedMace, "Brightbeak"),
            new Unique(ItemType.OneHandedMace, "Lavianga's Wisdom"),
            new Unique(ItemType.OneHandedMace, "Flesh-Eater"),
            new Unique(ItemType.OneHandedMace, "Clayshaper"),
            new Unique(ItemType.OneHandedMace, "Frostbreath"),
            new Unique(ItemType.OneHandedMace, "Cameria's Maul"),
            new Unique(ItemType.OneHandedMace, "Mjölner"),
            new Unique(ItemType.OneHandedMace, "Callinellus Malleus"),
            new Unique(ItemType.TwoHandedMace, "Hrimnor's Hymn"),
            new Unique(ItemType.TwoHandedMace, "Quecholli"),
            new Unique(ItemType.TwoHandedMace, "Geofri's Baptism"),
            new Unique(ItemType.TwoHandedMace, "Hrimnor's Dirge"),
            new Unique(ItemType.TwoHandedMace, "Chober Chaber"),
            new Unique(ItemType.TwoHandedMace, "Trypanon"),
            new Unique(ItemType.TwoHandedMace, "Jorrhast's Blacksteel"),
            new Unique(ItemType.TwoHandedMace, "Voidhome"),
            new Unique(ItemType.TwoHandedMace, "Marohi Erqi"),
            new Unique(ItemType.TwoHandedMace, "Brain Rattler"),
            new Unique(ItemType.TwoHandedMace, "Tidebreaker"),
            new Unique(ItemType.TwoHandedMace, "Kongor's Undying Rage"),
            new Unique(ItemType.Sceptre, "Axiom Perpetuum"),
            new Unique(ItemType.Sceptre, "Spine of the First Claimant"),
            new Unique(ItemType.Sceptre, "Brutus' Lead Sprinkler"),
            new Unique(ItemType.Sceptre, "Bitterdream"),
            new Unique(ItemType.Sceptre, "The Dark Seer"),
            new Unique(ItemType.Sceptre, "Nycta's Lantern"),
            new Unique(ItemType.Sceptre, "The Supreme Truth"),
            new Unique(ItemType.Sceptre, "Death's Hand"),
            new Unique(ItemType.Sceptre, "Singularity"),
            new Unique(ItemType.Sceptre, "Doon Cuebiyari"),
            new Unique(ItemType.Sceptre, "Breath of the Council"),
            new Unique(ItemType.Sceptre, "Mon'tregul's Grasp"),
            new Unique(ItemType.Sceptre, "Doryani's Catalyst"),
            new Unique(ItemType.OneHandedSword, "Redbeak"),
            new Unique(ItemType.OneHandedSword, "The Princess"),
            new Unique(ItemType.OneHandedSword, "The Tempestuous Steel"),
            new Unique(ItemType.OneHandedSword, "Lakishu's Blade"),
            new Unique(ItemType.OneHandedSword, "The Goddess Scorned"),
            new Unique(ItemType.OneHandedSword, "Ephemeral Edge"),
            new Unique(ItemType.OneHandedSword, "Severed in Sleep"),
            new Unique(ItemType.OneHandedSword, "Innsbury Edge"),
            new Unique(ItemType.OneHandedSword, "The Goddess Unleashed"),
            new Unique(ItemType.OneHandedSword, "Prismatic Eclipse"),
            new Unique(ItemType.OneHandedSword, "Ichimonji"),
            new Unique(ItemType.OneHandedSword, "Scaeva"),
            new Unique(ItemType.OneHandedSword, "Hyaon's Fury"),
            new Unique(ItemType.OneHandedSword, "Rebuke of the Vaal"),
            new Unique(ItemType.OneHandedSword, "Varunastra"),
            new Unique(ItemType.OneHandedSword, "Dreamfeather"),
            new Unique(ItemType.OneHandedSword, "Razor of the Seventh Sun"),
            new Unique(ItemType.OneHandedSword, "Rigwald's Command"),
            new Unique(ItemType.OneHandedSword, "United in Dream"),
            new Unique(ItemType.OneHandedThrustingSword, "The Goddess Bound"),
            new Unique(ItemType.OneHandedThrustingSword, "Aurumvorax"),
            new Unique(ItemType.OneHandedThrustingSword, "Fidelitas' Spike"),
            new Unique(ItemType.OneHandedThrustingSword, "Ewar's Mirage"),
            new Unique(ItemType.OneHandedThrustingSword, "Chitus' Needle"),
            new Unique(ItemType.OneHandedThrustingSword, "Daresso's Passion"),
            new Unique(ItemType.OneHandedThrustingSword, "Cospri's Malice"),
            new Unique(ItemType.TwoHandedSword, "Shiversting"),
            new Unique(ItemType.TwoHandedSword, "Edge of Madness"),
            new Unique(ItemType.TwoHandedSword, "Queen's Decree"),
            new Unique(ItemType.TwoHandedSword, "Queen's Escape"),
            new Unique(ItemType.TwoHandedSword, "Rigwald's Charge"),
            new Unique(ItemType.TwoHandedSword, "Terminus Est"),
            new Unique(ItemType.TwoHandedSword, "Hiltless"),
            new Unique(ItemType.TwoHandedSword, "The Dancing Dervish"),
            new Unique(ItemType.TwoHandedSword, "Kondo's Pride"),
            new Unique(ItemType.TwoHandedSword, "Doomsower"),
            new Unique(ItemType.TwoHandedSword, "Oro's Sacrifice"),
            new Unique(ItemType.TwoHandedSword, "Starforge"),
            new Unique(ItemType.Flask, "Blood of the Karui"),
            new Unique(ItemType.Flask, "Doedre's Elixir"),
            new Unique(ItemType.Flask, "Zerphi's Last Breath"),
            new Unique(ItemType.Flask, "Lavianga's Spirit"),
            new Unique(ItemType.Flask, "Divination Distillate"),
            new Unique(ItemType.Flask, "The Writhing Jar"),
            new Unique(ItemType.Flask, "The Wise Oak"),
            new Unique(ItemType.Flask, "Sin's Rebirth"),
            new Unique(ItemType.Flask, "Coruscating Elixir"),
            new Unique(ItemType.Flask, "Taste of Hate"),
            new Unique(ItemType.Flask, "Kiara's Determination"),
            new Unique(ItemType.Flask, "Forbidden Taste"),
            new Unique(ItemType.Flask, "Lion's Roar"),
            new Unique(ItemType.Flask, "The Overflowing Chalice"),
            new Unique(ItemType.Flask, "The Sorrow of the Divine"),
            new Unique(ItemType.Flask, "Rotgut"),
            new Unique(ItemType.Flask, "Witchfire Brew"),
            new Unique(ItemType.Flask, "Atziri's Promise"),
            new Unique(ItemType.Flask, "Dying Sun"),
            new Unique(ItemType.Flask, "Rumi's Concoction"),
            new Unique(ItemType.Flask, "Vessel of Vinktar"),
            new Unique(ItemType.Jewel, "Anatomical Knowledge"),
            new Unique(ItemType.Jewel, "Apparitions"),
            new Unique(ItemType.Jewel, "Army of Bones"),
            new Unique(ItemType.Jewel, "Assassin's Haste"),
            new Unique(ItemType.Jewel, "Brawn"),
            new Unique(ItemType.Jewel, "Brute Force Solution"),
            new Unique(ItemType.Jewel, "Careful Planning"),
            new Unique(ItemType.Jewel, "Cheap Construction"),
            new Unique(ItemType.Jewel, "Clear Mind"),
            new Unique(ItemType.Jewel, "Coated Shrapnel"),
            new Unique(ItemType.Jewel, "Cold Steel"),
            new Unique(ItemType.Jewel, "Collateral Damage"),
            new Unique(ItemType.Jewel, "Conqueror's Efficiency"),
            new Unique(ItemType.Jewel, "Conqueror's Longevity"),
            new Unique(ItemType.Jewel, "Conqueror's Potency"),
            new Unique(ItemType.Jewel, "Dead Reckoning"),
            new Unique(ItemType.Jewel, "Efficient Training"),
            new Unique(ItemType.Jewel, "Eldritch Knowledge"),
            new Unique(ItemType.Jewel, "Emperor's Cunning"),
            new Unique(ItemType.Jewel, "Emperor's Mastery"),
            new Unique(ItemType.Jewel, "Emperor's Might"),
            new Unique(ItemType.Jewel, "Emperor's Wit"),
            new Unique(ItemType.Jewel, "Energised Armour"),
            new Unique(ItemType.Jewel, "Energy From Within"),
            new Unique(ItemType.Jewel, "Fertile Mind"),
            new Unique(ItemType.Jewel, "Fight for Survival"),
            new Unique(ItemType.Jewel, "Fireborn"),
            new Unique(ItemType.Jewel, "First Snow"),
            new Unique(ItemType.Jewel, "Fluid Motion"),
            new Unique(ItemType.Jewel, "Fortified Legion"),
            new Unique(ItemType.Jewel, "Fragile Bloom"),
            new Unique(ItemType.Jewel, "Frozen Trail"),
            new Unique(ItemType.Jewel, "Grand Spectrum"),
            new Unique(ItemType.Jewel, "Growing Agony"),
            new Unique(ItemType.Jewel, "Hair Trigger"),
            new Unique(ItemType.Jewel, "Healthy Mind"),
            new Unique(ItemType.Jewel, "Hidden Potential"),
            new Unique(ItemType.Jewel, "Hotfooted"),
            new Unique(ItemType.Jewel, "Inertia"),
            new Unique(ItemType.Jewel, "Inevitability"),
            new Unique(ItemType.Jewel, "Inspired Learning"),
            new Unique(ItemType.Jewel, "Intuitive Leap"),
            new Unique(ItemType.Jewel, "Izaro's Turmoil"),
            new Unique(ItemType.Jewel, "Lioneye's Fall"),
            new Unique(ItemType.Jewel, "Malicious Intent"),
            new Unique(ItemType.Jewel, "Mantra of Flames"),
            new Unique(ItemType.Jewel, "Martial Artistry"),
            new Unique(ItemType.Jewel, "Might and Influence"),
            new Unique(ItemType.Jewel, "Might in All Forms"),
            new Unique(ItemType.Jewel, "Omen on the Winds"),
            new Unique(ItemType.Jewel, "Overwhelming Odds"),
            new Unique(ItemType.Jewel, "Pitch Darkness"),
            new Unique(ItemType.Jewel, "Poacher's Aim"),
            new Unique(ItemType.Jewel, "Primordial Eminence"),
            new Unique(ItemType.Jewel, "Primordial Harmony"),
            new Unique(ItemType.Jewel, "Primordial Might"),
            new Unique(ItemType.Jewel, "Pugilist"),
            new Unique(ItemType.Jewel, "Rain of Splinters"),
            new Unique(ItemType.Jewel, "Rapid Expansion"),
            new Unique(ItemType.Jewel, "Reckless Defence"),
            new Unique(ItemType.Jewel, "Ring of Blades"),
            new Unique(ItemType.Jewel, "Rolling Flames"),
            new Unique(ItemType.Jewel, "Shattered Chains"),
            new Unique(ItemType.Jewel, "Spire of Stone"),
            new Unique(ItemType.Jewel, "Spirit Guards"),
            new Unique(ItemType.Jewel, "Spirited Response"),
            new Unique(ItemType.Jewel, "Static Electricity"),
            new Unique(ItemType.Jewel, "Steel Spirit"),
            new Unique(ItemType.Jewel, "Sudden Ignition"),
            new Unique(ItemType.Jewel, "Survival Instincts"),
            new Unique(ItemType.Jewel, "Survival Secrets"),
            new Unique(ItemType.Jewel, "Survival Skills"),
            new Unique(ItemType.Jewel, "The Anima Stone"),
            new Unique(ItemType.Jewel, "The Blue Dream"),
            new Unique(ItemType.Jewel, "The Blue Nightmare"),
            new Unique(ItemType.Jewel, "The Green Dream"),
            new Unique(ItemType.Jewel, "The Green Nightmare"),
            new Unique(ItemType.Jewel, "The Red Dream"),
            new Unique(ItemType.Jewel, "The Red Nightmare"),
            new Unique(ItemType.Jewel, "The Vigil"),
            new Unique(ItemType.Jewel, "Unending Hunger"),
            new Unique(ItemType.Jewel, "Unstable Payload"),
            new Unique(ItemType.Jewel, "Violent Dead"),
            new Unique(ItemType.Jewel, "Volley Fire"),
            new Unique(ItemType.Jewel, "Warlord's Reach"),
            new Unique(ItemType.Jewel, "Weight of the Empire"),
            new Unique(ItemType.Jewel, "Wildfire"),
            new Unique(ItemType.Jewel, "Winter Burial"),
            new Unique(ItemType.Jewel, "Winter's Bounty"),
            new Unique(ItemType.Jewel, "Ancient Waystones"),
            new Unique(ItemType.Jewel, "Atziri's Reign"),
            new Unique(ItemType.Jewel, "Blood Sacrifice"),
            new Unique(ItemType.Jewel, "Brittle Barrier"),
            new Unique(ItemType.Jewel, "Chill of Corruption"),
            new Unique(ItemType.Jewel, "Combustibles"),
            new Unique(ItemType.Jewel, "Corrupted Energy"),
            new Unique(ItemType.Jewel, "Fevered Mind"),
            new Unique(ItemType.Jewel, "Fragility"),
            new Unique(ItemType.Jewel, "Hungry Abyss"),
            new Unique(ItemType.Jewel, "Mutated Growth"),
            new Unique(ItemType.Jewel, "Pacifism"),
            new Unique(ItemType.Jewel, "Powerlessness"),
            new Unique(ItemType.Jewel, "Sacrificial Harvest"),
            new Unique(ItemType.Jewel, "Self-Flagellation"),
            new Unique(ItemType.Jewel, "Vaal Sentencing"),
            new Unique(ItemType.Jewel, "Weight of Sin"),
            new Unique(ItemType.Jewel, "Assassin's Haste"),
            new Unique(ItemType.Jewel, "Conqueror's Efficiency"),
            new Unique(ItemType.Jewel, "Conqueror's Longevity"),
            new Unique(ItemType.Jewel, "Conqueror's Potency"),
            new Unique(ItemType.Jewel, "Poacher's Aim"),
            new Unique(ItemType.Jewel, "Survival Instincts"),
            new Unique(ItemType.Jewel, "Survival Secrets"),
            new Unique(ItemType.Jewel, "Survival Skills"),
            new Unique(ItemType.Jewel, "Warlord's Reach"),
            new Unique(ItemType.Jewel, "Emperor's Cunning"),
            new Unique(ItemType.Jewel, "Emperor's Mastery"),
            new Unique(ItemType.Jewel, "Emperor's Might"),
            new Unique(ItemType.Jewel, "Emperor's Wit"),
            new Unique(ItemType.Jewel, "Cannibalistic Habits"),
            new Unique(ItemType.Jewel, "Coated Weapons"),
            new Unique(ItemType.Jewel, "Controlled Energy"),
            new Unique(ItemType.Jewel, "Dark Thoughts"),
            new Unique(ItemType.Jewel, "Mantra of Force"),
            new Unique(ItemType.Jewel, "Miser of Misery"),
            new Unique(ItemType.Jewel, "Projected Force"),
            new Unique(ItemType.Jewel, "Selfless Leadership"),
            new Unique(ItemType.Jewel, "Specialised"),
            new Unique(ItemType.Jewel, "Stimulated Growth"),
            new Unique(ItemType.Jewel, "Sturdy Growth"),
            new Unique(ItemType.Jewel, "Surplus"),
            new Unique(ItemType.Jewel, "Vampire's Might"),
            new Unique(ItemType.Jewel, "Wisdom of the Path Not Taken"),
            new Unique(ItemType.Jewel, "Zerphi's Youth"),
            new Unique(ItemType.Map, "Acton's Nightmare"),
            new Unique(ItemType.Map, "Caer Blaidd, Wolfpack's Den"),
            new Unique(ItemType.Map, "Death and Taxes"),
            new Unique(ItemType.Map, "Hall of Grandmasters"),
            new Unique(ItemType.Map, "Hallowed Ground"),
            new Unique(ItemType.Map, "Maelström of Chaos"),
            new Unique(ItemType.Map, "Mao Kun"),
            new Unique(ItemType.Map, "Oba's Cursed Trove"),
            new Unique(ItemType.Map, "Olmec's Sanctum"),
            new Unique(ItemType.Map, "Poorjoy's Asylum"),
            new Unique(ItemType.Map, "The Coward's Trial"),
            new Unique(ItemType.Map, "The Perandus Manor"),
            new Unique(ItemType.Map, "The Putrid Cloister"),
            new Unique(ItemType.Map, "The Vinktar Square"),
            new Unique(ItemType.Map, "Untainted Paradise"),
            new Unique(ItemType.Map, "Vaults of Atziri"),
            new Unique(ItemType.Map, "Whakawairua Tuahu"),
        };

    }

    public struct Unique
    {
        public ItemType ItemType { get; }
        public string ItemName { get; }

        public Unique(ItemType itemType, string itemName)
        {
            ItemType = itemType;
            ItemName = itemName;
        }
    }
}