using System;
using System.Linq;

namespace POEStash
{
    public enum ItemType
    {
        Unknown,
        Amulet,
        Talisman,
        Ring,
        Belt,
        Quiver,
        BodyArmour,
        Boots,
        Gloves,
        Helmet,
        Shield,
        Bow,
        Claw,
        Dagger,
        OneHandedAxe,
        OneHandedMace,
        OneHandedSword,
        Sceptre,
        Staff,
        OneHandedThrustringSword,
        TwoHandedAxe,
        TwoHandedMace,
        TwoHandedSword,
        Wand,
        Jewel,
        Map,
        MapFragment,
        SkillGem,
        DivinationCard,
        Currency,
        Flask
    }

    public static class BaseTypes
    {
        public static ItemType GetItemType(string typeString)
        {
            if (Matches(BaseTypesAmulets.BaseTypes, typeString))                  return ItemType.Amulet;
            if (Matches(BaseTypesRings.BaseTypes, typeString))                    return ItemType.Ring;
            if (Matches(BaseTypesBelt.BaseTypes, typeString))                     return ItemType.Belt;
            if (Matches(BaseTypesQuivers.BaseTypes, typeString))                  return ItemType.Quiver;
            if (Matches(BaseTypesTalismans.BaseTypes, typeString))                return ItemType.Talisman;
            if (Matches(BaseTypesBodyArmour.BaseTypes, typeString))               return ItemType.BodyArmour;
            if (Matches(BaseTypesBoots.BaseTypes, typeString))                    return ItemType.Boots;
            if (Matches(BaseTypesGloves.BaseTypes, typeString))                   return ItemType.Gloves;
            if (Matches(BaseTypesHelmets.BaseTypes, typeString))                  return ItemType.Helmet;
            if (Matches(BaseTypesShields.BaseTypes, typeString))                  return ItemType.Shield;
            if (Matches(BaseTypesBows.BaseTypes, typeString))                     return ItemType.Bow;
            if (Matches(BaseTypesClaws.BaseTypes, typeString))                    return ItemType.Claw;
            if (Matches(BaseTypesDaggers.BaseTypes, typeString))                  return ItemType.Dagger;
            if (Matches(BaseTypesOneHandedAxes.BaseTypes, typeString))            return ItemType.OneHandedAxe;
            if (Matches(BaseTypesOneHandedMaces.BaseTypes, typeString))           return ItemType.OneHandedMace;
            if (Matches(BaseTypesOneHandedSwords.BaseTypes, typeString))          return ItemType.OneHandedSword;
            if (Matches(BaseTypesSceptres.BaseTypes, typeString))                 return ItemType.Sceptre;
            if (Matches(BaseTypesStaffs.BaseTypes, typeString))                   return ItemType.Staff;
            if (Matches(BaseTypesThrustingOneHandedSwords.BaseTypes, typeString)) return ItemType.OneHandedThrustringSword;
            if (Matches(BaseTypesTwoHandedAxes.BaseTypes, typeString))            return ItemType.TwoHandedAxe;
            if (Matches(BaseTypesTwoHandedMaces.BaseTypes, typeString))           return ItemType.TwoHandedMace;
            if (Matches(BaseTypesTwoHandedSwords.BaseTypes, typeString))          return ItemType.TwoHandedSword;
            if (Matches(BaseTypesWands.BaseTypes, typeString))                    return ItemType.Wand;
            if (Matches(BaseTypesJewels.BaseTypes, typeString))                   return ItemType.Jewel;
            if (Matches(BaseTypesMaps.BaseTypes, typeString))                     return ItemType.Map;
            if (Matches(BaseTypesMapFragments.BaseTypes, typeString)) return ItemType.MapFragment;
            if (Matches(BaseTypesSkillGems.BaseTypes, typeString))                return ItemType.SkillGem;
            if (Matches(BaseTypesDivinationCards.BaseTypes, typeString))          return ItemType.DivinationCard;
            if (Matches(BaseTypesCurrencies.BaseTypes, typeString)) return ItemType.Currency;
            if (Matches(BaseTypesFlasks.BaseTypes, typeString)) return ItemType.Flask;

            return ItemType.Unknown;
        }

        private static bool Matches(string[] baseTypes, string typeString)
        {
            foreach (string baseType in baseTypes)
            {
                if (typeString.IndexOf(baseType, 0, StringComparison.OrdinalIgnoreCase) != -1)
                {
                    return true;
                }
            }

            return false;
        }
    }

    public static class BaseTypesAmulets
    {
        public static string[] BaseTypes =
        {
            "Coral Amulet",
            "Paua Amulet",
            "Amber Amulet",
            "Jade Amulet",
            "Lapis Amulet",
            "Gold Amulet",
            "Agate Amulet",
            "Citrine Amulet",
            "Turquoise Amulet",
            "Onyx Amulet",
            "Marble Amulet",
            "Blue Pearl Amulet"
        };
    }

    public static class BaseTypesRings
    {
        public static string[] BaseTypes =
        {
            "Breach Ring",
            "Iron Ring",
            "Coral Ring",
            "Paua Ring",
            "Sapphire Ring",
            "Topaz Ring",
            "Golden Hoop",
            "Jet Ring",
            "Ruby Ring",
            "Gold Ring",
            "Two-Stone Ring",
            "Diamond Ring",
            "Moonstone Ring",
            "Prismatic Ring",
            "Amethyst Ring",
            "Unset Ring",
            "Steel Ring",
            "Opal Ring",
        };
    }

    public static class BaseTypesBelt
    {
        public static string[] BaseTypes =
        {
            "Chain Belt",
            "Rustic Sash",
            "Heavy Belt",
            "Leather Belt",
            "Cloth Belt",
            "Studded Belt",
            "Vanguard Belt",
            "Crystal Belt"
        };
    }

    public static class BaseTypesQuivers
    {
        public static string[] BaseTypes =
        {
            "Two-Point Arrow Quiver",
            "Serrated Arrow Quiver",
            "Sharktooth Arrow Quiver",
            "Blunt Arrow Quiver",
            "Fire Arrow Quiver",
            "Broadhead Arrow Quiver",
            "Penetrating Arrow Quiver",
            "Spike-Point Arrow Quiver",
        };
    }

    public static class BaseTypesTalismans
    {
        public static string[] BaseTypes =
        {
            "Spinefuse Talisman",
            "Mandible Talisman",
            "Hexclaw Talisman",
            "Primal Skull Talisman",
            "Wereclaw Talisman",
            "Splitnewt Talisman",
            "Clutching Talisman",
            "Avian Twins Talisman",
            "Fangjaw Talisman",
            "Horned Talisman",
            "Three Rat Talisman",
            "Monkey Twins Talisman",
            "Longtooth Talisman",
            "Rotfeather Talisman",
            "Monkey Paw Talisman",
            "Three Hands Talisman",
            "Jet Amulet",
            "Black Maw Talisman",
            "Bonespire Talisman",
            "Ashscale Talisman",
            "Lone Antler Talisman",
            "Deep One Talisman",
            "Breakrib Talisman",
            "Deadhand Talisman",
            "Undying Flesh Talisman",
            "Rot Head Talisman",
            "Writhing Talisman",
            "Chrysalis Talisman",
            "Greatwolf Talisman"
        };
    }

    public static class BaseTypesBodyArmour
    {
        public static string[] BaseTypes =
        {
            "Plate Vest",
            "Shabby Jerkin",
            "Simple Robe",
            "Chainmail Vest",
            "Scale Vest",
            "Padded Vest",
            "Chestplate",
            "Light Brigandine",
            "Chainmail Tunic",
            "Oiled Vest",
            "Strapped Leather",
            "Silken Vest",
            "Scale Doublet",
            "Ringmail Coat",
            "Copper Plate",
            "Buckskin Tunic",
            "Padded Jacket",
            "Scholar's Robe",
            "Infantry Brigandine",
            "Chainmail Doublet",
            "War Plate",
            "Oiled Coat",
            "Wild Leather",
            "Silken Garb",
            "Full Plate",
            "Mage's Vestment",
            "Scarlet Raiment",
            "Full Ringmail",
            "Full Scale Armour",
            "Full Leather",
            "Soldier's Brigandine",
            "Silk Robe",
            "Waxed Garb",
            "Arena Plate",
            "Sun Leather",
            "Full Chainmail",
            "Holy Chainmail",
            "Lordly Plate",
            "Thief's Garb",
            "Cabalist Regalia",
            "Field Lamellar",
            "Bone Armour",
            "Eelskin Tunic",
            "Bronze Plate",
            "Sage's Robe",
            "Wyrmscale Doublet",
            "Latticed Ringmail",
            "Quilted Jacket",
            "Silken Wrap",
            "Battle Plate",
            "Frontier Leather",
            "Hussar Brigandine",
            "Crusader Chainmail",
            "Sleek Coat",
            "Sun Plate",
            "Conjurer's Vestment",
            "Glorious Leather",
            "Full Wyrmscale",
            "Ornate Ringmail",
            "Crimson Raiment",
            "Colosseum Plate",
            "Coronal Leather",
            "Spidersilk Robe",
            "Commander's Brigandine",
            "Chain Hauberk",
            "Lacquered Garb",
            "Majestic Plate",
            "Cutthroat's Garb",
            "Destroyer Regalia",
            "Battle Lamellar",
            "Devout Chainmail",
            "Crypt Armour",
            "Savant's Robe",
            "Sharkskin Tunic",
            "Golden Plate",
            "Dragonscale Doublet",
            "Loricated Ringmail",
            "Sentinel Jacket",
            "Necromancer Silks",
            "Crusader Plate",
            "Destiny Leather",
            "Desert Brigandine",
            "Conquest Chainmail",
            "Occultist's Vestment",
            "Exquisite Leather",
            "Astral Plate",
            "Varnished Coat",
            "Full Dragonscale",
            "Elegant Ringmail",
            "Zodiac Leather",
            "Gladiator Plate",
            "Widowsilk Robe",
            "Blood Raiment",
            "General's Brigandine",
            "Saint's Hauberk",
            "Glorious Plate",
            "Assassin's Garb",
            "Vaal Regalia",
            "Sadist Garb",
            "Triumphant Lamellar",
            "Saintly Chainmail",
            "Carnal Armour",
            "Sacrificial Garb"
        };
    }

    public static class BaseTypesBoots
    {
        public static string[] BaseTypes =
        {
            "Iron Greaves",
            "Rawhide Boots",
            "Wool Shoes",
            "Chain Boots",
            "Wrapped Boots",
            "Leatherscale Boots",
            "Velvet Slippers",
            "Steel Greaves",
            "Goathide Boots",
            "Ringmail Boots",
            "Strapped Boots",
            "Ironscale Boots",
            "Deerskin Boots",
            "Silk Slippers",
            "Plated Greaves",
            "Clasped Boots",
            "Mesh Boots",
            "Bronzescale Boots",
            "Scholar Boots",
            "Reinforced Greaves",
            "Nubuck Boots",
            "Shackled Boots",
            "Steelscale Boots",
            "Riveted Boots",
            "Antique Greaves",
            "Satin Slippers",
            "Eelskin Boots",
            "Zealot Boots",
            "Trapper Boots",
            "Serpentscale Boots",
            "Samite Slippers",
            "Sharkskin Boots",
            "Ancient Greaves",
            "Ambush Boots",
            "Soldier Boots",
            "Wyrmscale Boots",
            "Conjurer Boots",
            "Goliath Greaves",
            "Carnal Boots",
            "Shagreen Boots",
            "Legion Boots",
            "Hydrascale Boots",
            "Arcanist Slippers",
            "Vaal Greaves",
            "Stealth Boots",
            "Assassin's Boots",
            "Crusader Boots",
            "Dragonscale Boots",
            "Sorcerer Boots",
            "Titan Greaves",
            "Slink Boots",
            "Murder Boots",
            "Two-Toned Boots",
        };
    }

    public static class BaseTypesGloves
    {
        public static string[] BaseTypes =
        {
            "Iron Gauntlets",
            "Rawhide Gloves",
            "Wool Gloves",
            "Fishscale Gauntlets",
            "Wrapped Mitts",
            "Chain Gloves",
            "Goathide Gloves",
            "Plated Gauntlets",
            "Velvet Gloves",
            "Ironscale Gauntlets",
            "Strapped Mitts",
            "Ringmail Gloves",
            "Deerskin Gloves",
            "Bronze Gauntlets",
            "Silk Gloves",
            "Bronzescale Gauntlets",
            "Clasped Mitts",
            "Mesh Gloves",
            "Nubuck Gloves",
            "Steel Gauntlets",
            "Embroidered Gloves",
            "Trapper Mitts",
            "Steelscale Gauntlets",
            "Riveted Gloves",
            "Eelskin Gloves",
            "Antique Gauntlets",
            "Satin Gloves",
            "Zealot Gloves",
            "Serpentscale Gauntlets",
            "Ambush Mitts",
            "Sharkskin Gloves",
            "Samite Gloves",
            "Ancient Gauntlets",
            "Wyrmscale Gauntlets",
            "Carnal Mitts",
            "Soldier Gloves",
            "Goliath Gauntlets",
            "Shagreen Gloves",
            "Conjurer Gloves",
            "Legion Gloves",
            "Assassin's Mitts",
            "Hydrascale Gauntlets",
            "Arcanist Gloves",
            "Stealth Gloves",
            "Vaal Gauntlets",
            "Crusader Gloves",
            "Murder Mitts",
            "Dragonscale Gauntlets",
            "Titan Gauntlets",
            "Sorcerer Gloves",
            "Slink Gloves",
            "Gripped Gloves",
            "Fingerless Silk Gloves",
            "Spiked Gloves",
        };
    }

    public static class BaseTypesHelmets
    {
        public static string[] BaseTypes =
        {
            "Iron Hat",
            "Vine Circlet",
            "Leather Cap",
            "Scare Mask",
            "Battered Helm",
            "Rusted Coif",
            "Cone Helmet",
            "Iron Circlet",
            "Tricorne",
            "Plague Mask",
            "Soldier Helmet",
            "Sallet",
            "Iron Mask",
            "Torture Cage",
            "Barbute Helmet",
            "Leather Hood",
            "Great Helmet",
            "Visored Sallet",
            "Close Helmet",
            "Tribal Circlet",
            "Festival Mask",
            "Wolf Pelt",
            "Crusader Helmet",
            "Gilded Sallet",
            "Bone Circlet",
            "Gladiator Helmet",
            "Golden Mask",
            "Secutor Helm",
            "Aventail Helmet",
            "Raven Mask",
            "Lunaris Circlet",
            "Reaver Helmet",
            "Hunter Hood",
            "Fencer Helm",
            "Zealot Helmet",
            "Callous Mask",
            "Noble Tricorne",
            "Steel Circlet",
            "Siege Helmet",
            "Lacquered Helmet",
            "Regicide Mask",
            "Great Crown",
            "Necromancer Circlet",
            "Ursine Pelt",
            "Samite Helmet",
            "Harlequin Mask",
            "Magistrate Crown",
            "Fluted Bascinet",
            "Solaris Circlet",
            "Silken Hood",
            "Ezomyte Burgonet",
            "Vaal Mask",
            "Pig-Faced Bascinet",
            "Prophet Crown",
            "Sinner Tricorne",
            "Mind Cage",
            "Royal Burgonet",
            "Deicide Mask",
            "Nightmare Bascinet",
            "Praetor Crown",
            "Hubris Circlet",
            "Eternal Burgonet",
            "Lion Pelt",
            "Bone Helmet",
        };
    }

    public static class BaseTypesShields
    {
        public static string[] BaseTypes =
        {
            "Splintered Tower Shield",
            "Goathide Buckler",
            "Twig Spirit Shield",
            "Spiked Bundle",
            "Corroded Tower Shield",
            "Rotted Round Shield",
            "Plank Kite Shield",
            "Pine Buckler",
            "Yew Spirit Shield",
            "Rawhide Tower Shield",
            "Fir Round Shield",
            "Driftwood Spiked Shield",
            "Linden Kite Shield",
            "Bone Spirit Shield",
            "Painted Buckler",
            "Cedar Tower Shield",
            "Reinforced Kite Shield",
            "Alloyed Spiked Shield",
            "Studded Round Shield",
            "Hammered Buckler",
            "Tarnished Spirit Shield",
            "Copper Tower Shield",
            "Layered Kite Shield",
            "Scarlet Round Shield",
            "Burnished Spiked Shield",
            "Jingling Spirit Shield",
            "War Buckler",
            "Reinforced Tower Shield",
            "Splendid Round Shield",
            "Ornate Spiked Shield",
            "Brass Spirit Shield",
            "Ceremonial Kite Shield",
            "Gilded Buckler",
            "Painted Tower Shield",
            "Walnut Spirit Shield",
            "Oak Buckler",
            "Buckskin Tower Shield",
            "Maple Round Shield",
            "Redwood Spiked Shield",
            "Etched Kite Shield",
            "Ivory Spirit Shield",
            "Enameled Buckler",
            "Mahogany Tower Shield",
            "Ancient Spirit Shield",
            "Spiked Round Shield",
            "Compound Spiked Shield",
            "Corrugated Buckler",
            "Steel Kite Shield",
            "Bronze Tower Shield",
            "Chiming Spirit Shield",
            "Crimson Round Shield",
            "Polished Spiked Shield",
            "Battle Buckler",
            "Laminated Kite Shield",
            "Girded Tower Shield",
            "Thorium Spirit Shield",
            "Sovereign Spiked Shield",
            "Golden Buckler",
            "Baroque Round Shield",
            "Angelic Kite Shield",
            "Crested Tower Shield",
            "Lacewood Spirit Shield",
            "Ironwood Buckler",
            "Alder Spiked Shield",
            "Shagreen Tower Shield",
            "Teak Round Shield",
            "Branded Kite Shield",
            "Fossilised Spirit Shield",
            "Lacquered Buckler",
            "Ebony Tower Shield",
            "Champion Kite Shield",
            "Vaal Spirit Shield",
            "Spiny Round Shield",
            "Ezomyte Spiked Shield",
            "Vaal Buckler",
            "Ezomyte Tower Shield",
            "Mosaic Kite Shield",
            "Harmonic Spirit Shield",
            "Cardinal Round Shield",
            "Mirrored Spiked Shield",
            "Crusader Buckler",
            "Colossal Tower Shield",
            "Archon Kite Shield",
            "Titanium Spirit Shield",
            "Imperial Buckler",
            "Supreme Spiked Shield",
            "Pinnacle Tower Shield",
            "Elegant Round Shield",
        };
    }

    public static class BaseTypesBows
    {
        public static string[] BaseTypes =
        {
            "Crude Bow",
            "Short Bow",
            "Long Bow",
            "Composite Bow",
            "Recurve Bow",
            "Bone Bow",
            "Royal Bow",
            "Death Bow",
            "Grove Bow",
            "Reflex Bow",
            "Decurve Bow",
            "Compound Bow",
            "Sniper Bow",
            "Ivory Bow",
            "Highborn Bow",
            "Decimation Bow",
            "Thicket Bow",
            "Steelwood Bow",
            "Citadel Bow",
            "Ranger Bow",
            "Assassin Bow",
            "Spine Bow",
            "Imperial Bow",
            "Harbinger Bow",
            "Maraketh Bow",
        };
    }

    public static class BaseTypesClaws
    {
        public static string[] BaseTypes =
        {
            "Nailed Fist",
            "Sharktooth Claw",
            "Awl",
            "Cat's Paw",
            "Blinder",
            "Timeworn Claw",
            "Sparkling Claw",
            "Fright Claw",
            "Double Claw",
            "Thresher Claw",
            "Gouger",
            "Tiger's Paw",
            "Gut Ripper",
            "Prehistoric Claw",
            "Noble Claw",
            "Eagle Claw",
            "Twin Claw",
            "Great White Claw",
            "Throat Stabber",
            "Hellion's Paw",
            "Eye Gouger",
            "Vaal Claw",
            "Imperial Claw",
            "Terror Claw",
            "Gemini Claw",
        };
    }

    public static class BaseTypesDaggers
    {
        public static string[] BaseTypes =
        {
            "Glass Shank",
            "Skinning Knife",
            "Carving Knife",
            "Stiletto",
            "Boot Knife",
            "Copper Kris",
            "Skean",
            "Imp Dagger",
            "Flaying Knife",
            "Prong Dagger",
            "Butcher Knife",
            "Poignard",
            "Boot Blade",
            "Golden Kris",
            "Royal Skean",
            "Fiend Dagger",
            "Trisula",
            "Gutting Knife",
            "Slaughter Knife",
            "Ambusher",
            "Ezomyte Dagger",
            "Platinum Kris",
            "Imperial Skean",
            "Demon Dagger",
            "Sai",
        };
    }

    public static class BaseTypesOneHandedAxes
    {
        public static string[] BaseTypes =
        {
            "Rusted Hatchet",
            "Jade Hatchet",
            "Boarding Axe",
            "Cleaver",
            "Broad Axe",
            "Arming Axe",
            "Decorative Axe",
            "Spectral Axe",
            "Etched Hatchet",
            "Jasper Axe",
            "Tomahawk",
            "Wrist Chopper",
            "War Axe",
            "Chest Splitter",
            "Ceremonial Axe",
            "Wraith Axe",
            "Engraved Hatchet",
            "Karui Axe",
            "Siege Axe",
            "Reaver Axe",
            "Butcher Axe",
            "Vaal Hatchet",
            "Royal Axe",
            "Infernal Axe",
            "Runic Hatchet",
        };
    }

    public static class BaseTypesOneHandedMaces
    {
        public static string[] BaseTypes =
        {
            "Driftwood Club",
            "Tribal Club",
            "Spiked Club",
            "Stone Hammer",
            "War Hammer",
            "Bladed Mace",
            "Ceremonial Mace",
            "Dream Mace",
            "Wyrm Mace",
            "Petrified Club",
            "Barbed Club",
            "Rock Breaker",
            "Battle Hammer",
            "Flanged Mace",
            "Ornate Mace",
            "Phantom Mace",
            "Dragon Mace",
            "Ancestral Club",
            "Tenderizer",
            "Gavel",
            "Legion Hammer",
            "Pernarch",
            "Auric Mace",
            "Nightmare Mace",
            "Behemoth Mace",
        };
    }

    public static class BaseTypesOneHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Rusted Sword",
            "Copper Sword",
            "Sabre",
            "Broad Sword",
            "War Sword",
            "Ancient Sword",
            "Elegant Sword",
            "Dusk Blade",
            "Hook Sword",
            "Variscite Blade",
            "Cutlass",
            "Baselard",
            "Battle Sword",
            "Elder Sword",
            "Graceful Sword",
            "Twilight Blade",
            "Grappler",
            "Gemstone Sword",
            "Corsair Sword",
            "Gladius",
            "Legion Sword",
            "Vaal Blade",
            "Eternal Sword",
            "Midnight Blade",
            "Tiger Hook",
        };
    }

    public static class BaseTypesSceptres
    {
        public static string[] BaseTypes =
        {
            "Driftwood Sceptre",
            "Darkwood Sceptre",
            "Bronze Sceptre",
            "Quartz Sceptre",
            "Iron Sceptre",
            "Ochre Sceptre",
            "Ritual Sceptre",
            "Shadow Sceptre",
            "Grinning Fetish",
            "Horned Sceptre",
            "Sekhem",
            "Crystal Sceptre",
            "Lead Sceptre",
            "Blood Sceptre",
            "Royal Sceptre",
            "Abyssal Sceptre",
            "Stag Sceptre",
            "Karui Sceptre",
            "Tyrant's Sekhem",
            "Opal Sceptre",
            "Platinum Sceptre",
            "Vaal Sceptre",
            "Carnal Sceptre",
            "Void Sceptre",
            "Sambar Sceptre",
        };
    }

    public static class BaseTypesStaffs
    {
        public static string[] BaseTypes =
        {
            "Gnarled Branch",
            "Primitive Staff",
            "Long Staff",
            "Iron Staff",
            "Coiled Staff",
            "Royal Staff",
            "Vile Staff",
            "Crescent Staff",
            "Woodful Staff",
            "Quarterstaff",
            "Military Staff",
            "Serpentine Staff",
            "Highborn Staff",
            "Foul Staff",
            "Moon Staff",
            "Primordial Staff",
            "Lathi",
            "Ezomyte Staff",
            "Maelström Staff",
            "Imperial Staff",
            "Judgement Staff",
            "Eclipse Staff",
        };
    }

    public static class BaseTypesThrustingOneHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Rusted Spike",
            "Whalebone Rapier",
            "Battered Foil",
            "Basket Rapier",
            "Jagged Foil",
            "Antique Rapier",
            "Elegant Foil",
            "Thorn Rapier",
            "Smallsword",
            "Wyrmbone Rapier",
            "Burnished Foil",
            "Estoc",
            "Serrated Foil",
            "Primeval Rapier",
            "Fancy Foil",
            "Apex Rapier",
            "Courtesan Sword",
            "Dragonbone Rapier",
            "Tempered Foil",
            "Pecoraro",
            "Spiraled Foil",
            "Vaal Rapier",
            "Jewelled Foil",
            "Harpy Rapier",
            "Dragoon Sword",
        };
    }

    public static class BaseTypesTwoHandedAxes
    {
        public static string[] BaseTypes =
        {
            "Stone Axe",
            "Jade Chopper",
            "Woodsplitter",
            "Poleaxe",
            "Double Axe",
            "Gilded Axe",
            "Shadow Axe",
            "Dagger Axe",
            "Jasper Chopper",
            "Timber Axe",
            "Headsman Axe",
            "Labrys",
            "Noble Axe",
            "Abyssal Axe",
            "Karui Chopper",
            "Talon Axe",
            "Sundering Axe",
            "Ezomyte Axe",
            "Vaal Axe",
            "Despot Axe",
            "Void Axe",
            "Fleshripper",
        };
    }

    public static class BaseTypesTwoHandedMaces
    {
        public static string[] BaseTypes =
        {
            "Driftwood Maul",
            "Tribal Maul",
            "Mallet",
            "Sledgehammer",
            "Jagged Maul",
            "Brass Maul",
            "Fright Maul",
            "Morning Star",
            "Totemic Maul",
            "Great Mallet",
            "Steelhead",
            "Spiny Maul",
            "Plated Maul",
            "Dread Maul",
            "Solar Maul",
            "Karui Maul",
            "Colossus Mallet",
            "Piledriver",
            "Meatgrinder",
            "Imperial Maul",
            "Terror Maul",
            "Coronal Maul",
        };
    }

    public static class BaseTypesTwoHandedSwords
    {
        public static string[] BaseTypes =
        {
            "Corroded Blade",
            "Longsword",
            "Bastard Sword",
            "Two-Handed Sword",
            "Etched Greatsword",
            "Ornate Sword",
            "Spectral Sword",
            "Curved Blade",
            "Butcher Sword",
            "Footman Sword",
            "Highland Blade",
            "Engraved Greatsword",
            "Tiger Sword",
            "Wraith Sword",
            "Lithe Blade",
            "Headman's Sword",
            "Reaver Sword",
            "Ezomyte Blade",
            "Vaal Greatsword",
            "Lion Sword",
            "Infernal Sword",
            "Exquisite Blade",
        };
    }

    public static class BaseTypesWands
    {
        public static string[] BaseTypes =
        {
            "Driftwood Wand",
            "Goat's Horn",
            "Carved Wand",
            "Quartz Wand",
            "Spiraled Wand",
            "Sage Wand",
            "Pagan Wand",
            "Faun's Horn",
            "Engraved Wand",
            "Crystal Wand",
            "Serpent Wand",
            "Omen Wand",
            "Heathen Wand",
            "Demon's Horn",
            "Imbued Wand",
            "Opal Wand",
            "Tornado Wand",
            "Prophecy Wand",
            "Profane Wand",
        };
    }

    public static class BaseTypesJewels
    {
        public static string[] BaseTypes =
        {
            "Cobalt Jewel",
            "Crimson Jewel",
            "Viridian Jewel",
            "Prismatic Jewel",
        };
    }

    public static class BaseTypesMaps
    {
        public static string[] BaseTypes =
        {
            "Arcade Map",
            "Crystal Ore Map",
            "Desert Map",
            "Jungle Valley Map",
            "Beach Map",
            "Factory Map",
            "Ghetto Map",
            "Oasis Map",
            "Arid Lake Map",
            "Cavern Map",
            "Channel Map",
            "Grotto Map",
            "Marshes Map",
            "Sewer Map",
            "Vaal Pyramid Map",
            "Academy Map",
            "Acid Lakes Map",
            "Dungeon Map",
            "Graveyard Map",
            "Phantasmagoria Map",
            "Villa Map",
            "Waste Pool Map",
            "Burial Chambers Map",
            "Dunes Map",
            "Mesa Map",
            "Peninsula Map",
            "Pit Map",
            "Primordial Pool Map",
            "Spider Lair Map",
            "Tower Map",
            "Canyon Map",
            "Quarry Map",
            "Racecourse Map",
            "Ramparts Map",
            "Spider Forest Map",
            "Strand Map",
            "Thicket Map",
            "Vaal City Map",
            "Wharf Map",
            "Arachnid Tomb Map",
            "Armoury Map",
            "Ashen Wood Map",
            "Castle Ruins Map",
            "Catacombs Map",
            "Cells Map",
            "Mud Geyser Map",
            "Arachnid Nest Map",
            "Arena Map",
            "Atoll Map",
            "Barrows Map",
            "Bog Map",
            "Cemetery Map",
            "Pier Map",
            "Shore Map",
            "Tropical Island Map",
            "Coves Map",
            "Crypt Map",
            "Museum Map",
            "Orchard Map",
            "Overgrown Shrine Map",
            "Promenade Map",
            "Reef Map",
            "Temple Map",
            "Arsenal Map",
            "Colonnade Map",
            "Courtyard Map",
            "Malformation Map",
            "Quay Map",
            "Malformation Map",
            "Terrace Map",
            "Underground River Map",
            "Bazaar Map",
            "Chateau Map",
            "Excavation Map",
            "Precinct Map",
            "Torture Chamber Map",
            "Underground Sea Map",
            "Wasteland Map",
            "Crematorium Map",
            "Estuary Map",
            "Ivory Temple Map",
            "Necropolis Map",
            "Plateau Map",
            "Residence Map",
            "Shipyard Map",
            "Vault Map",
            "Beacon Map",
            "Gorge Map",
            "High Gardens Map",
            "Lair Map",
            "Plaza Map",
            "Scriptorium Map",
            "Sulphur Wastes Map",
            "Waterways Map",
            "Maze Map",
            "Mineral Pools Map",
            "Palace Map",
            "Shrine Map",
            "Springs Map",
            "Volcano Map",
            "Abyss Map",
            "Colosseum Map",
            "Core Map",
            "Dark Forest Map",
            "Overgrown Ruin Map",
            "Forge of the Phoenix Map",
            "Lair of the Hydra Map",
            "Maze of the Minotaur Map",
            "Pit of the Chimera Map",
            "Vaal Temple Map",
        };
    }

    public static class BaseTypesMapFragments
    {
        public static string[] BaseTypes =
        {
            "Sacrifice at Dusk",
            "Sacrifice at Midnight",
            "Sacrifice at Dawn",
            "Sacrifice at Noon",
            "Mortal Grief",
            "Mortal Rage",
            "Mortal Hope",
            "Mortal Ignorance",
            "Volkuur's Key",
            "Eber's Key",
            "Yriel's Key",
            "Inya's Key",
            "Fragment of the Hydra",
            "Fragment of the Phoenix",
            "Fragment of the Minotaur",
            "Fragment of the Chimera",
        };
    }

    public static class BaseTypesSkillGems
    {
        public static string[] BaseTypes =
        {
            "Abyssal Cry",
            "Added Chaos Damage Support",
            "Added Cold Damage Support",
            "Added Fire Damage Support",
            "Added Lightning Damage Support",
            "Additional Accuracy Support",
            "Ancestral Protector",
            "Ancestral Warchief",
            "Anger",
            "Animate Guardian",
            "Animate Weapon",
            "Arc",
            "Arctic Armour",
            "Arctic Breath",
            "Assassin's Mark",
            "Ball Lightning",
            "Barrage",
            "Bear Trap",
            "Blade Flurry",
            "Blade Vortex",
            "Bladefall",
            "Blasphemy Support",
            "Blast Rain",
            "Blight",
            "Blind Support",
            "Blink Arrow",
            "Block Chance Reduction Support",
            "Blood Magic Support",
            "Blood Rage",
            "Bloodlust Support",
            "Bone Offering",
            "Burning Arrow",
            "Cast On Critical Strike Support",
            "Cast on Death Support",
            "Cast on Melee Kill Support",
            "Cast when Damage Taken Support",
            "Cast when Stunned Support",
            "Cast while Channelling Support",
            "Caustic Arrow",
            "Chain Support",
            "Chance to Flee Support",
            "Chance to Ignite Support",
            "Clarity",
            "Cleave",
            "Cluster Traps Support",
            "Cold Penetration Support",
            "Cold Snap",
            "Cold to Fire Support",
            "Concentrated Effect Support",
            "Conductivity",
            "Contagion",
            "Controlled Destruction Support",
            "Conversion Trap",
            "Convocation",
            "Culling Strike Support",
            "Curse On Hit Support",
            "Cyclone",
            "Decoy Totem",
            "Desecrate",
            "Determination",
            "Detonate Dead",
            "Detonate Mines",
            "Devouring Totem",
            "Discharge",
            "Discipline",
            "Dominating Blow",
            "Double Strike",
            "Dual Strike",
            "Earthquake",
            "Elemental Focus Support",
            "Elemental Hit",
            "Elemental Proliferation Support",
            "Elemental Weakness",
            "Empower Support",
            "Endurance Charge on Melee Stun Support",
            "Enduring Cry",
            "Enfeeble",
            "Enhance Support",
            "Enlighten Support",
            "Essence Drain",
            "Ethereal Knives",
            "Explosive Arrow",
            "Faster Attacks Support",
            "Faster Casting Support",
            "Faster Projectiles Support",
            "Fire Nova Mine",
            "Fire Penetration Support",
            "Fire Trap",
            "Fireball",
            "Firestorm",
            "Flame Dash",
            "Flame Surge",
            "Flame Totem",
            "Flameblast",
            "Flammability",
            "Flesh Offering",
            "Flicker Strike",
            "Fork Support",
            "Fortify Support",
            "Freeze Mine",
            "Freezing Pulse",
            "Frenzy",
            "Frost Blades",
            "Frost Bomb",
            "Frost Wall",
            "Frostbite",
            "Frostbolt",
            "Generosity Support",
            "Glacial Cascade",
            "Glacial Hammer",
            "Grace",
            "Greater Multiple Projectiles Support",
            "Ground Slam",
            "Haste",
            "Hatred",
            "Heavy Strike",
            "Herald of Ash",
            "Herald of Ice",
            "Herald of Thunder",
            "Hypothermia Support",
            "Ice Bite Support",
            "Ice Crash",
            "Ice Nova",
            "Ice Shot",
            "Ice Spear",
            "Ice Trap",
            "Immortal Call",
            "Incinerate",
            "Increased Area of Effect Support",
            "Increased Burning Damage Support",
            "Increased Critical Damage Support",
            "Increased Critical Strikes Support",
            "Increased Duration Support",
            "Infernal Blow",
            "Innervate Support",
            "Iron Grip Support",
            "Iron Will Support",
            "Item Quantity Support",
            "Item Rarity Support",
            "Kinetic Blast",
            "Knockback Support",
            "Lacerate",
            "Leap Slam",
            "Less Duration Support",
            "Lesser Multiple Projectiles Support",
            "Life Gain on Hit Support",
            "Life Leech Support",
            "Lightning Arrow",
            "Lightning Penetration Support",
            "Lightning Strike",
            "Lightning Tendrils",
            "Lightning Trap",
            "Lightning Warp",
            "Magma Orb",
            "Mana Leech Support",
            "Melee Damage on Full Life Support",
            "Melee Physical Damage Support",
            "Melee Splash Support",
            "Minefield Support",
            "Minion Damage Support",
            "Minion Life Support",
            "Minion Speed Support",
            "Minion and Totem Elemental Resistance Support",
            "Mirror Arrow",
            "Molten Shell",
            "Molten Strike",
            "Multiple Traps Support",
            "Multistrike Support",
            "Orb of Storms",
            "Phase Run",
            "Physical Projectile Attack Damage Support",
            "Physical to Lightning Support",
            "Pierce Support",
            "Poacher's Mark",
            "Point Blank Support",
            "Poison Support",
            "Portal",
            "Power Charge On Critical Support",
            "Power Siphon",
            "Projectile Weakness",
            "Puncture",
            "Punishment",
            "Purity of Elements",
            "Purity of Fire",
            "Purity of Ice",
            "Purity of Lightning",
            "Rain of Arrows",
            "Raise Spectre",
            "Raise Zombie",
            "Rallying Cry",
            "Ranged Attack Totem Support",
            "Rapid Decay Support",
            "Reave",
            "Reckoning",
            "Reduced Mana Support",
            "Rejuvenation Totem",
            "Remote Mine Support",
            "Righteous Fire",
            "Riposte",
            "Scorching Ray",
            "Searing Bond",
            "Shield Charge",
            "Shock Nova",
            "Shockwave Totem",
            "Shrapnel Shot",
            "Siege Ballista",
            "Slower Projectiles Support",
            "Smoke Mine",
            "Spark",
            "Spectral Throw",
            "Spell Echo Support",
            "Spell Totem Support",
            "Spirit Offering",
            "Split Arrow",
            "Static Strike",
            "Storm Call",
            "Stun Support",
            "Summon Chaos Golem",
            "Summon Flame Golem",
            "Summon Ice Golem",
            "Summon Lightning Golem",
            "Summon Raging Spirit",
            "Summon Skeletons",
            "Summon Stone Golem",
            "Sunder",
            "Sweep",
            "Tempest Shield",
            "Temporal Chains",
            "Tornado Shot",
            "Trap Cooldown Support",
            "Trap Support",
            "Trap and Mine Damage Support",
            "Vaal Arc",
            "Vaal Breach",
            "Vaal Burning Arrow",
            "Vaal Clarity",
            "Vaal Cold Snap",
            "Vaal Cyclone",
            "Vaal Detonate Dead",
            "Vaal Discipline",
            "Vaal Double Strike",
            "Vaal Fireball",
            "Vaal Flameblast",
            "Vaal Glacial Hammer",
            "Vaal Grace",
            "Vaal Ground Slam",
            "Vaal Haste",
            "Vaal Ice Nova",
            "Vaal Immortal Call",
            "Vaal Lightning Strike",
            "Vaal Lightning Trap",
            "Vaal Lightning Warp",
            "Vaal Molten Shell",
            "Vaal Power Siphon",
            "Vaal Rain of Arrows",
            "Vaal Reave",
            "Vaal Righteous Fire",
            "Vaal Spark",
            "Vaal Spectral Throw",
            "Vaal Storm Call",
            "Vaal Summon Skeletons",
            "Vengeance",
            "Vigilant Strike",
            "Viper Strike",
            "Vitality",
            "Void Manipulation Support",
            "Vortex",
            "Vulnerability",
            "Warlord's Mark",
            "Weapon Elemental Damage Support",
            "Whirling Blades",
            "Wild Strike",
            "Wither",
            "Wrath",
        };
    }

    public static class BaseTypesDivinationCards
    {
        public static string[] BaseTypes =
        {
            "Abandoned Wealth",
            "The Aesthete",
            "Anarchy's Price",
            "The Arena Champion",
            "The Artist",
            "Assassin's Favour",
            "Audacity",
            "The Avenger",
            "The Battle Born",
            "The Betrayal",
            "Birth of the Three",
            "Blind Venture",
            "The Body",
            "Boundless Realms",
            "Bowyer's Dream",
            "The Brittle Emperor",
            "The Carrion Crow",
            "The Cartographer",
            "The Cataclysm",
            "The Catalyst",
            "The Celestial Justicar",
            "The Chains that Bind",
            "Chaotic Disposition",
            "The Conduit",
            "Coveted Possession",
            "The Dapper Prodigy",
            "The Dark Mage",
            "Death",
            "The Demoness",
            "Destined to Crumble",
            "The Devastator",
            "The Doctor",
            "Doedre's Madness",
            "The Doppelganger",
            "The Dragon",
            "The Dragon's Heart",
            "The Drunken Aristocrat",
            "Dying Anguish",
            "Earth Drinker",
            "Emperor's Luck",
            "The Encroaching Darkness",
            "The Enlightened",
            "The Ethereal",
            "The Explorer",
            "The Feast",
            "The Fiend",
            "The Fletcher",
            "The Flora's Gift",
            "The Fox",
            "The Gambler",
            "The Gemcutter",
            "Gemcutter's Promise",
            "The Gentleman",
            "Gift of the Gemling Queen",
            "The Gladiator",
            "Glimmer of Hope",
            "Grave Knowledge",
            "Her Mask",
            "The Hermit",
            "Heterochromia",
            "The Hoarder",
            "Hope",
            "House of Mirrors",
            "Hubris",
            "Humility",
            "The Hunger",
            "Hunter's Resolve",
            "Hunter's Reward",
            "The Immortal",
            "The Incantation",
            "The Inoculated",
            "The Inventor",
            "Jack in the Box",
            "The King's Blade",
            "The King's Heart",
            "Lantador's Lost Love",
            "Last Hope",
            "The Last One Standing",
            "The Lich",
            "The Lion",
            "The Lord in Black",
            "Lost Worlds",
            "The Lover",
            "Loyalty",
            "Lucky Connections",
            "The Mercenary",
            "Merciless Armament",
            "The Metalsmith's Gift",
            "A Mother's Parting Gift",
            "The Offering",
            "The One With All",
            "The Pack Leader",
            "The Pact",
            "The Poet",
            "Pride Before the Fall",
            "Prosperity",
            "The Queen",
            "The Rabid Rhoa",
            "Rain of Chaos",
            "Rats",
            "The Risk",
            "The Road to Power",
            "The Scarred Meadow",
            "The Scholar",
            "Scholar of the Seas",
            "Shard of Fate",
            "The Sigil",
            "The Siren",
            "The Spoiled Prince",
            "The Summoner",
            "The Sun",
            "The Surgeon",
            "The Surveyor",
            "The Survivalist",
            "The Thaumaturgist",
            "Three Faces in the Dark",
            "The Throne",
            "Time-Lost Relic",
            "The Tower",
            "The Traitor",
            "Thunderous Skies",
            "Tranquillity",
            "Treasure Hunter",
            "The Trial",
            "Turn the Other Cheek",
            "The Twins",
            "The Union",
            "The Vast",
            "Vinia's Token",
            "The Void",
            "Volatile Power",
            "The Warden",
            "The Warlord",
            "The Watcher",
            "Wealth and Power",
            "The Wind",
            "The Wolf's Shadow",
            "The Wrath",
        };
    }

    public static class BaseTypesFlasks
    {
        public static string[] BaseTypes =
        {
            "Small Life Flask",
            "Medium Life Flask",
            "Large Life Flask",
            "Greater Life Flask",
            "Grand Life Flask",
            "Giant Life Flask",
            "Colossal Life Flask",
            "Sacred Life Flask",
            "Hallowed Life Flask",
            "Sanctified Life Flask",
            "Divine Life Flask",
            "Eternal Life Flask",
            "Small Mana Flask",
            "Medium Mana Flask",
            "Large Mana Flask",
            "Greater Mana Flask",
            "Grand Mana Flask",
            "Giant Mana Flask",
            "Colossal Mana Flask",
            "Sacred Mana Flask",
            "Hallowed Mana Flask",
            "Sanctified Mana Flask",
            "Divine Mana Flask",
            "Eternal Mana Flask",
            "Small Hybrid Flask",
            "Medium Hybrid Flask",
            "Large Hybrid Flask",
            "Colossal Hybrid Flask",
            "Sacred Hybrid Flask",
            "Hallowed Hybrid Flask",
            "Quicksilver Flask",
            "Bismuth Flask",
            "Stibnite Flask",
            "Amethyst Flask",
            "Ruby Flask",
            "Sapphire Flask",
            "Topaz Flask",
            "Silver Flask",
            "Aquamarine Flask",
            "Granite Flask",
            "Jade Flask",
            "Quartz Flask",
            "Sulphur Flask",
            "Basalt Flask",
            "Diamond Flask",
        };
    }

    public static class BaseTypesCurrencies
    {
        public static string[] BaseTypes =
        {
            "Albino Rhoa Feather",
            "Apprentice Cartographer's Seal",
            "Apprentice Cartographer's Sextant",
            "Armourer's Scrap",
            "Blacksmith's Whetstone",
            "Blessed Orb",
            "Blessing of Chayula",
            "Blessing of Esh",
            "Blessing of Tul",
            "Blessing of Uul-Netol",
            "Blessing of Xoph",
            "Cartographer's Chisel",
            "Chaos Orb",
            "Chromatic Orb",
            "Divine Orb",
            "Exalted Orb",
            "Gemcutter's Prism",
            "Glassblower's Bauble",
            "Jeweller's Orb",
            "Journeyman Cartographer's Seal",
            "Journeyman Cartographer's Sextant",
            "Master Cartographer's Seal",
            "Master Cartographer's Sextant",
            "Mirror of Kalandra",
            "Orb of Alchemy",
            "Orb of Alteration",
            "Orb of Augmentation",
            "Orb of Chance",
            "Orb of Fusing",
            "Orb of Regret",
            "Orb of Scouring",
            "Orb of Transmutation",
            "Perandus Coin",
            "Portal Scroll",
            "Prophecy",
            "Regal Orb",
            "Scroll of Wisdom",
            "Silver Coin",
            "Stacked Deck",
            "Unshaping Orb",
            "Vaal Orb",
            "Alchemy Shard",
            "Alteration Shard",
            "Scroll Fragment",
            "Splinter of Chayula",
            "Splinter of Esh",
            "Splinter of Tul",
            "Splinter of Uul-Netol",
            "Splinter of Xoph",
            "Transmutation Shard",
        };
    }
}